import type { AbilityIconAccent, AbilityIconFrame, AbilityIconProfile, AbilityIconSymbol } from './types';

export type AbilityIconOverride = Pick<AbilityIconProfile, 'symbol' | 'frame' | 'accent'>;

const icon = (
  symbol: AbilityIconSymbol,
  frame: AbilityIconFrame,
  accent: AbilityIconAccent,
): AbilityIconOverride => ({ symbol, frame, accent });

/**
 * Explicit icon art direction for every playable ability. The key mirrors the
 * stable runtime ability ID, so icon changes do not depend on hash ordering.
 */
export const ABILITY_ICON_OVERRIDES: Record<string, AbilityIconOverride> = {
  'ember_arcanist.spark_lash': icon('orb', 'diamond', 'spark'),
  'ember_arcanist.cinder_lance': icon('bolt', 'diamond', 'spark'),
  'ember_arcanist.kindle_hex': icon('flame', 'round', 'spark'),
  'ember_arcanist.soot_veil': icon('vortex', 'round', 'dot'),
  'ember_arcanist.flashstep': icon('spear', 'diamond', 'chevron'),
  'ember_arcanist.pyre_circle': icon('shockwave', 'burst', 'spark'),
  'ember_arcanist.white_cautery': icon('cross', 'shield', 'cross'),
  'ember_arcanist.furnace_heart': icon('aura', 'round', 'spark'),
  'ember_arcanist.ashen_cataclysm': icon('bolt', 'diamond', 'tear'),
  'ember_arcanist.phoenix_collapse': icon('meteor', 'burst', 'spark'),

  'hex_inquisitor.brand_shot': icon('dagger', 'diamond', 'dot'),
  'hex_inquisitor.interrogate': icon('blade', 'round', 'spark'),
  'hex_inquisitor.silver_snare': icon('chain', 'rune', 'dot'),
  'hex_inquisitor.relic_oil': icon('chalice', 'round', 'spark'),
  'hex_inquisitor.purging_slash': icon('blade', 'round', 'tear'),
  'hex_inquisitor.black_powder_step': icon('dagger', 'diamond', 'chevron'),
  'hex_inquisitor.stake_the_guilty': icon('spear', 'burst', 'tear'),
  'hex_inquisitor.ash_ward': icon('shield', 'shield', 'cross'),
  'hex_inquisitor.torch_of_scorn': icon('flame', 'burst', 'spark'),
  'hex_inquisitor.final_sentence': icon('dagger', 'burst', 'tear'),

  'sunfire_templar.solar_edict': icon('aura', 'shield', 'spark'),
  'sunfire_templar.bastion_edict': icon('shield', 'shield', 'cross'),
  'sunfire_templar.pursuit_edict': icon('banner', 'shield', 'chevron'),
  'sunfire_templar.sunbrand_strike': icon('hammer', 'round', 'spark'),
  'sunfire_templar.shield_of_noon': icon('shield', 'shield', 'cross'),
  'sunfire_templar.rallying_rebuke': icon('banner', 'round', 'dot'),
  'sunfire_templar.banner_rush': icon('spear', 'diamond', 'chevron'),
  'sunfire_templar.radiant_counter': icon('cross', 'round', 'spark'),
  'sunfire_templar.heavenrend_sweep': icon('shockwave', 'burst', 'tear'),
  'sunfire_templar.daybreak_standard': icon('banner', 'burst', 'spark'),

  'battle_prelate.litany_of_strikes': icon('hammer', 'round', 'spark'),
  'battle_prelate.sanctified_blow': icon('hammer', 'round', 'cross'),
  'battle_prelate.martyr_s_ward': icon('shield', 'shield', 'cross'),
  'battle_prelate.penance_step': icon('spear', 'diamond', 'chevron'),
  'battle_prelate.hymn_of_resolve': icon('aura', 'round', 'cross'),
  'battle_prelate.reliquary_smash': icon('shockwave', 'burst', 'dot'),
  'battle_prelate.judgment_of_ash': icon('bolt', 'diamond', 'spark'),
  'battle_prelate.redemption_surge': icon('chalice', 'burst', 'tear'),
  'battle_prelate.icon_of_wrath': icon('totem', 'rune', 'spark'),
  'battle_prelate.last_homily': icon('cross', 'burst', 'spark'),

  'stoneguard.oath_bind': icon('banner', 'shield', 'cross'),
  'stoneguard.grudge_axes': icon('axe', 'diamond', 'dot'),
  'stoneguard.clanwall': icon('shield', 'round', 'dot'),
  'stoneguard.bitter_reprisal': icon('axe', 'burst', 'tear'),
  'stoneguard.runebound_mail': icon('shield', 'rune', 'cross'),
  'stoneguard.stone_march': icon('rune', 'round', 'chevron'),
  'stoneguard.holdfast': icon('shield', 'shield', 'cross'),
  'stoneguard.vengeful_hook': icon('chain', 'diamond', 'dot'),
  'stoneguard.hearthguard_vow': icon('shield', 'rune', 'cross'),
  'stoneguard.book_of_wrongs': icon('shockwave', 'burst', 'tear'),

  'doomseeker.death_oath': icon('axe', 'shield', 'spark'),
  'doomseeker.twin_hew': icon('axe', 'round', 'dot'),
  'doomseeker.skullsplit_leap': icon('fang', 'diamond', 'spark'),
  'doomseeker.exhausting_swing': icon('axe', 'burst', 'tear'),
  'doomseeker.bloodhowl': icon('aura', 'round', 'spark'),
  'doomseeker.grim_pursuit': icon('fang', 'shield', 'chevron'),
  'doomseeker.reckless_arc': icon('shockwave', 'burst', 'spark'),
  'doomseeker.no_respite': icon('fang', 'round', 'tear'),
  'doomseeker.doom_roar': icon('vortex', 'round', 'dot'),
  'doomseeker.final_reckoning': icon('skull', 'burst', 'tear'),

  'glyphbinder.rune_of_mending': icon('cross', 'rune', 'cross'),
  'glyphbinder.rune_of_warding': icon('shield', 'rune', 'cross'),
  'glyphbinder.rune_of_cleaving': icon('mark', 'rune', 'dot'),
  'glyphbinder.anchor_sigil': icon('snare', 'rune', 'dot'),
  'glyphbinder.oath_script': icon('rune', 'rune', 'spark'),
  'glyphbinder.master_rune_of_hearth': icon('totem', 'rune', 'cross'),
  'glyphbinder.master_rune_of_ruin': icon('shockwave', 'burst', 'spark'),
  'glyphbinder.stoneword': icon('rune', 'diamond', 'dot'),
  'glyphbinder.ancestor_s_favor': icon('cross', 'rune', 'tear'),
  'glyphbinder.ancestor_lexicon': icon('rune', 'burst', 'spark'),

  'siegewright.deploy_gunlet': icon('turret', 'rune', 'dot'),
  'siegewright.crank_charge': icon('turret', 'round', 'spark'),
  'siegewright.buckshot_salvo': icon('bomb', 'round', 'dot'),
  'siegewright.fragment_bomb': icon('bomb', 'burst', 'spark'),
  'siegewright.harpoon_line': icon('chain', 'diamond', 'dot'),
  'siegewright.landmine_satchel': icon('snare', 'rune', 'spark'),
  'siegewright.grapnel_traverse': icon('chain', 'diamond', 'chevron'),
  'siegewright.armor_piercer': icon('arrow', 'diamond', 'tear'),
  'siegewright.ironstorm_battery': icon('turret', 'burst', 'spark'),
  'siegewright.fortified_redoubt': icon('turret', 'burst', 'cross'),

  'blade_savant.opening_form': icon('blade', 'round', 'dot'),
  'blade_savant.rising_form': icon('spear', 'diamond', 'chevron'),
  'blade_savant.perfect_form': icon('blade', 'burst', 'tear'),
  'blade_savant.warding_arc': icon('shield', 'shield', 'dot'),
  'blade_savant.moonstep': icon('blade', 'round', 'chevron'),
  'blade_savant.enchanted_edge': icon('blade', 'rune', 'spark'),
  'blade_savant.spiral_guard': icon('vortex', 'round', 'cross'),
  'blade_savant.mindward': icon('shield', 'rune', 'cross'),
  'blade_savant.aether_crossing': icon('spear', 'diamond', 'chevron'),
  'blade_savant.sevenfold_kata': icon('blade', 'burst', 'spark'),

  'pride_warden.hunter_s_mark': icon('mark', 'diamond', 'dot'),
  'pride_warden.pounce': icon('paw', 'diamond', 'chevron'),
  'pride_warden.pack_rend': icon('fang', 'round', 'spark'),
  'pride_warden.guardian_roar': icon('paw', 'round', 'dot'),
  'pride_warden.flanker_s_path': icon('paw', 'round', 'chevron'),
  'pride_warden.trophy_axe': icon('axe', 'burst', 'tear'),
  'pride_warden.wild_bond': icon('paw', 'shield', 'cross'),
  'pride_warden.snare_net': icon('snare', 'rune', 'dot'),
  'pride_warden.king_s_leap': icon('paw', 'burst', 'tear'),
  'pride_warden.pride_unleashed': icon('paw', 'burst', 'spark'),

  'aether_sage.starshard': icon('star', 'diamond', 'spark'),
  'aether_sage.verdant_current': icon('leaf', 'rune', 'cross'),
  'aether_sage.energy_weave': icon('aura', 'rune', 'spark'),
  'aether_sage.moonwell': icon('aura', 'burst', 'cross'),
  'aether_sage.sunpierce': icon('bolt', 'diamond', 'cross'),
  'aether_sage.merciful_veil': icon('shield', 'shield', 'cross'),
  'aether_sage.comet_snare': icon('meteor', 'rune', 'dot'),
  'aether_sage.tranquil_drift': icon('vortex', 'round', 'chevron'),
  'aether_sage.high_concord': icon('aura', 'burst', 'spark'),
  'aether_sage.celestial_equinox': icon('star', 'burst', 'cross'),

  'veil_ranger.longdraw': icon('arrow', 'diamond', 'dot'),
  'veil_ranger.running_shot': icon('arrow', 'diamond', 'chevron'),
  'veil_ranger.shadow_rush': icon('dagger', 'diamond', 'chevron'),
  'veil_ranger.barbed_volley': icon('arrow', 'burst', 'spark'),
  'veil_ranger.mist_walk': icon('vortex', 'shield', 'chevron'),
  'veil_ranger.eye_pierce': icon('eye', 'diamond', 'dot'),
  'veil_ranger.waylay_trap': icon('snare', 'rune', 'dot'),
  'veil_ranger.moonshot': icon('arrow', 'diamond', 'spark'),
  'veil_ranger.vengeance_mark': icon('mark', 'round', 'spark'),
  'veil_ranger.eclipse_hunt': icon('arrow', 'burst', 'tear'),

  'dreadsworn.aura_of_dread': icon('aura', 'shield', 'dot'),
  'dreadsworn.aura_of_ruin': icon('aura', 'rune', 'tear'),
  'dreadsworn.aura_of_dominion': icon('aura', 'shield', 'cross'),
  'dreadsworn.hexbrand_cleave': icon('claw', 'round', 'spark'),
  'dreadsworn.black_bastion': icon('shield', 'shield', 'cross'),
  'dreadsworn.tyrant_s_advance': icon('claw', 'diamond', 'chevron'),
  'dreadsworn.sunder_faith': icon('eye', 'round', 'dot'),
  'dreadsworn.warp_riposte': icon('claw', 'round', 'spark'),
  'dreadsworn.harrowing_roar': icon('shockwave', 'burst', 'dot'),
  'dreadsworn.crown_of_ruin': icon('crown', 'burst', 'tear'),

  'warped_reaver.mutate_claw': icon('claw', 'shield', 'spark'),
  'warped_reaver.mutate_crusher': icon('claw', 'shield', 'tear'),
  'warped_reaver.mutate_tendril': icon('chain', 'shield', 'dot'),
  'warped_reaver.flesh_hook': icon('chain', 'diamond', 'dot'),
  'warped_reaver.ravage_burst': icon('claw', 'burst', 'tear'),
  'warped_reaver.hideous_regrowth': icon('aura', 'rune', 'cross'),
  'warped_reaver.warpsprint': icon('claw', 'diamond', 'chevron'),
  'warped_reaver.bone_splinter': icon('fang', 'burst', 'spark'),
  'warped_reaver.mutation_shift': icon('vortex', 'rune', 'spark'),
  'warped_reaver.apotheosis_of_change': icon('vortex', 'burst', 'tear'),

  'void_magister.summon_idol': icon('totem', 'rune', 'spark'),
  'void_magister.warp_bolt': icon('orb', 'diamond', 'spark'),
  'void_magister.entropic_field': icon('vortex', 'burst', 'dot'),
  'void_magister.rift_pull': icon('vortex', 'rune', 'dot'),
  'void_magister.daemonfire_orb': icon('orb', 'diamond', 'spark'),
  'void_magister.hover_disc': icon('vortex', 'round', 'chevron'),
  'void_magister.unmake_armor': icon('mark', 'diamond', 'tear'),
  'void_magister.feed_the_idol': icon('totem', 'rune', 'spark'),
  'void_magister.warp_storm': icon('vortex', 'burst', 'tear'),
  'void_magister.grand_conjunction': icon('vortex', 'burst', 'spark'),

  'ruin_oracle.mark_of_vigor': icon('mark', 'rune', 'cross'),
  'ruin_oracle.harbinger_of_frailty': icon('mark', 'diamond', 'tear'),
  'ruin_oracle.soul_drain_rite': icon('bolt', 'diamond', 'cross'),
  'ruin_oracle.fetish_ward': icon('totem', 'rune', 'cross'),
  'ruin_oracle.madness_cant': icon('vortex', 'round', 'dot'),
  'ruin_oracle.blessing_of_ruin': icon('chalice', 'shield', 'cross'),
  'ruin_oracle.scourging_sigil': icon('rune', 'burst', 'tear'),
  'ruin_oracle.tether_of_agony': icon('chain', 'diamond', 'dot'),
  'ruin_oracle.prophecy_of_ash': icon('flame', 'diamond', 'tear'),
  'ruin_oracle.altar_of_the_raven': icon('totem', 'burst', 'spark'),

  'warbrute.sneaky_start': icon('axe', 'round', 'dot'),
  'warbrute.proper_wallop': icon('hammer', 'round', 'spark'),
  'warbrute.biggest_finish': icon('hammer', 'burst', 'tear'),
  'warbrute.shut_it': icon('shield', 'round', 'dot'),
  'warbrute.get_stuck_in': icon('spear', 'diamond', 'chevron'),
  'warbrute.wot_s_yours_is_mine': icon('shield', 'diamond', 'tear'),
  'warbrute.keep_smashin': icon('aura', 'round', 'spark'),
  'warbrute.boss_stomp': icon('shockwave', 'burst', 'dot'),
  'warbrute.you_watch_me': icon('shield', 'shield', 'cross'),
  'warbrute.boss_s_big_idea': icon('axe', 'burst', 'spark'),

  'fang_herder.loose_fang': icon('paw', 'diamond', 'dot'),
  'fang_herder.skewa_shot': icon('arrow', 'diamond', 'spark'),
  'fang_herder.bouncin_escape': icon('paw', 'diamond', 'chevron'),
  'fang_herder.bait_bag': icon('snare', 'rune', 'dot'),
  'fang_herder.spit_fang': icon('fang', 'shield', 'spark'),
  'fang_herder.hound_fang': icon('paw', 'shield', 'spark'),
  'fang_herder.big_chompa': icon('paw', 'burst', 'tear'),
  'fang_herder.needle_rain': icon('arrow', 'burst', 'spark'),
  'fang_herder.gobbo_prod': icon('paw', 'round', 'spark'),
  'fang_herder.fang_stampede': icon('paw', 'burst', 'chevron'),

  'bog_hexer.green_zap': icon('orb', 'diamond', 'spark'),
  'bog_hexer.patch_up': icon('cross', 'rune', 'cross'),
  'bog_hexer.crooked_beam': icon('bolt', 'diamond', 'cross'),
  'bog_hexer.bog_hop': icon('leaf', 'diamond', 'chevron'),
  'bog_hexer.sticky_curse': icon('snare', 'diamond', 'dot'),
  'bog_hexer.lucky_idol': icon('totem', 'rune', 'cross'),
  'bog_hexer.brain_banga': icon('eye', 'diamond', 'dot'),
  'bog_hexer.foul_brew': icon('orb', 'burst', 'cross'),
  'bog_hexer.mixed_medicine': icon('aura', 'rune', 'spark'),
  'bog_hexer.big_green_turnabout': icon('vortex', 'burst', 'cross'),

  'cleaver.whirly_chop': icon('shockwave', 'round', 'spark'),
  'cleaver.get_over_ere': icon('chain', 'diamond', 'dot'),
  'cleaver.mad_dash': icon('axe', 'diamond', 'chevron'),
  'cleaver.heavy_chop': icon('axe', 'burst', 'tear'),
  'cleaver.can_t_stop_me': icon('shield', 'shield', 'cross'),
  'cleaver.deep_cutz': icon('fang', 'burst', 'spark'),
  'cleaver.facebreaker': icon('hammer', 'round', 'dot'),
  'cleaver.keep_swingin': icon('aura', 'round', 'spark'),
  'cleaver.smash_pile': icon('shockwave', 'burst', 'dot'),
  'cleaver.red_mist': icon('axe', 'burst', 'tear'),

  'blood_dancer.vein_slice': icon('fang', 'round', 'spark'),
  'blood_dancer.poison_kiss': icon('venom', 'diamond', 'spark'),
  'blood_dancer.shadow_prowl': icon('vortex', 'shield', 'chevron'),
  'blood_dancer.razor_waltz': icon('dagger', 'round', 'spark'),
  'blood_dancer.crippling_cut': icon('dagger', 'round', 'dot'),
  'blood_dancer.heartseeker': icon('dagger', 'diamond', 'chevron'),
  'blood_dancer.red_caress': icon('fang', 'burst', 'tear'),
  'blood_dancer.mirror_veil': icon('vortex', 'shield', 'dot'),
  'blood_dancer.suffering_bloom': icon('venom', 'burst', 'spark'),
  'blood_dancer.crimson_ecstasy': icon('venom', 'burst', 'tear'),

  'dread_guard.spite_lash': icon('spear', 'round', 'dot'),
  'dread_guard.malice_guard': icon('mark', 'diamond', 'spark'),
  'dread_guard.void_buckler': icon('shield', 'shield', 'cross'),
  'dread_guard.glaive_hook': icon('chain', 'diamond', 'dot'),
  'dread_guard.cruel_intercept': icon('spear', 'diamond', 'chevron'),
  'dread_guard.sunder_grace': icon('mark', 'round', 'tear'),
  'dread_guard.torment_cage': icon('snare', 'burst', 'dot'),
  'dread_guard.bitter_harvest': icon('chalice', 'burst', 'tear'),
  'dread_guard.harrow_pike': icon('spear', 'diamond', 'spark'),
  'dread_guard.throne_s_contempt': icon('spear', 'burst', 'tear'),

  'dusk_weaver.umbral_bolt': icon('orb', 'diamond', 'dot'),
  'dusk_weaver.chill_of_dusk': icon('snare', 'diamond', 'dot'),
  'dusk_weaver.black_shard': icon('orb', 'diamond', 'tear'),
  'dusk_weaver.gloom_step': icon('vortex', 'round', 'chevron'),
  'dusk_weaver.agony_thread': icon('chain', 'diamond', 'tear'),
  'dusk_weaver.soul_freeze': icon('snare', 'rune', 'dot'),
  'dusk_weaver.void_rain': icon('vortex', 'burst', 'spark'),
  'dusk_weaver.cruel_harvest': icon('chalice', 'shield', 'cross'),
  'dusk_weaver.backlash_surge': icon('shockwave', 'burst', 'tear'),
  'dusk_weaver.midnight_cataclysm': icon('meteor', 'burst', 'spark'),

  'crimson_acolyte.siphon_cut': icon('dagger', 'round', 'dot'),
  'crimson_acolyte.blood_rite': icon('chalice', 'rune', 'cross'),
  'crimson_acolyte.pain_mirror': icon('mark', 'diamond', 'cross'),
  'crimson_acolyte.razor_prayer': icon('aura', 'round', 'cross'),
  'crimson_acolyte.cruel_embrace': icon('chain', 'diamond', 'dot'),
  'crimson_acolyte.scarlet_step': icon('dagger', 'diamond', 'chevron'),
  'crimson_acolyte.borrowed_vigor': icon('mark', 'round', 'tear'),
  'crimson_acolyte.covenant_of_knives': icon('dagger', 'burst', 'cross'),
  'crimson_acolyte.dark_communion': icon('chalice', 'burst', 'cross'),
  'crimson_acolyte.feast_of_the_shrine': icon('totem', 'burst', 'tear'),
} as const satisfies Record<string, AbilityIconOverride>;

export function getAbilityIconOverride(career: string, name: string): AbilityIconOverride | null {
  const key = `${slug(career)}.${slug(name)}`;
  return ABILITY_ICON_OVERRIDES[key] ?? null;
}

export function abilityIconOverrideKey(career: string, name: string): string {
  return `${slug(career)}.${slug(name)}`;
}

function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}
