import { existsSync } from 'node:fs';
import path from 'node:path';
import { repoRoot } from './toolchain';

export interface ParityFeature {
  id: string;
  title: string;
  sourceMode: 'local' | 'shared' | 'both';
  stage: 3 | 4 | 5 | 6;
  sourceFiles: string[];
  referenceTests: string[];
  acceptance: string[];
  unrealStatus: 'pending';
  developmentNotes?: string[];
}

const developmentNotes: Record<string, string[]> = {
  'gm-commands': ['The local development capital supports flight, bounded speed controls and collision-checked arrival return. Remote sessions reject these commands. Production authorization, arbitrary teleport, restoration and cooldown tools remain pending. See docs/unreal-gm-workbench.md.'],
  grounding: ['Aegis authored terrain and 145 residences plus 157 walls have sampled native collision evidence; full terrain, travel and Riftspire remain pending. See docs/unreal-capital-workbench.md.'],
  'gm-object-editor': ['A development-only in-game panel searches and places six house, two rowhouse and one wall model and edits Aegis buildings with authored collision, hide/restore, adjustable world grid/yaw alignment, exact position/full rotation/per-axis scale and revision checks. A bounded catalog uses stable deduplicated templates; pointer selection respects authored collision occlusion and registered identities. Construction survives fresh-process draft reload and additive map expansion. A separate purchased-kit pilot adds five models with authored mesh collision and material-preserving construction. Crownward is integrated as the main game development startup map with 8,704 kit placements and 14 models, original mountain terrain, 145 source house sites, five districts and the winding ascent to the castle. Native dispatch and five crafting station actors are assembled there. Windows editor-game and packaged default launches passed a 459-metre grounded ascent, native quest/station checks and fresh-process draft reload. Compact JSON preserves old draft compatibility within the 8 MB limit. The keep and courtyard stair modules face uphill, and the keep roof has an open stairwell; focused native walks cover ascent and descent to the roof and battlement. Full city traversal and remaining campaign actors remain pending. Bounds-aware creation and drop-to-surface handle offset import origins with authoritative collision traces, preserved mirrored scale, revision checks and undo/reload. A private recompiled copy of the unchanged legacy cloth material corrects the sampled packaged fabric; full material review remains open. Atomic repeated construction places 2-32 selected-model copies along local axes with oriented width/gap spacing, per-piece supports and whole-row undo/redo; generated identities survive draft reload. Whole-footprint slope fitting, drag previews, socket/assembly alignment, the remaining catalog, full tools and shared authorization remain pending. See docs/unreal-gm-workbench.md.'],
  'gm-publication': ['Local development drafts and undo/redo are implemented. Older drafts retain additive city imports; conflicting model/layout changes are rejected. Shared persistence, publication, version restore and conflicting baseline migrations remain pending. See docs/unreal-gm-workbench.md.'],
};

function feature(id: string, title: string, sourceMode: ParityFeature['sourceMode'], stage: ParityFeature['stage'],
  sourceFiles: string[], tests: string[], acceptance: string[]): ParityFeature {
  return { id, title, sourceMode, stage, sourceFiles, referenceTests: tests.map(test => `tests/${test}.test.ts`), acceptance,
    unrealStatus: 'pending', ...(developmentNotes[id] ? { developmentNotes: developmentNotes[id] } : {}) };
}

// These are behavior contracts, not a declaration that generated data is a native implementation.
export const parityFeatures: ParityFeature[] = [
  feature('characters', 'Full roster, creation, selection and preview', 'local', 3, ['src/data/careers.ts', 'src/services/local/characterLocal.ts'], ['characterLocal', 'characterPipelineContract'], ['Create/select all 48 race/class/body combinations with original player-facing names and correct realm capital.', 'Render equipped preview and world avatar with a suitable complex model; preserve per-character state isolation.']),
  feature('movement', 'Player movement, input and camera', 'local', 3, ['src/game/Player.ts', 'src/game/Camera.ts', 'src/game/Input.ts'], ['playerWallCollision', 'camera', 'keybindings'], ['Preserve strafe, jump/gravity, autorun cancellation, combined mouse movement, orbit/zoom and touch controls.', 'Preserve keyboard/mouse rebinding, conflicts, inversion and sensitivities; prevent gameplay input through modal/chat/GM/death UI.']),
  feature('grounding', 'Terrain, multilevel floors and collision', 'both', 5, ['src/world/CityElevation.ts', 'server/mapNavigation.ts'], ['cityElevation', 'cityLifts', 'keepEnclosureCollision'], ['Match ground on slopes, steps, roads, rotated/scaled walkable props, bridges and stacked floors.', 'Maintain camera clearance, closed-gate blocking, breach access and fall recovery.']),
  feature('abilities', 'All implemented class abilities', 'both', 3, ['src/game/abilities/abilityData.ts', 'src/game/Combat.ts'], ['abilityCatalog', 'abilityRuntime', 'abilityProgression'], ['Compare every one of 240 definitions, including the three explicitly unavailable summons.', 'Preserve ten stable slots, level unlocks, mana/class resource costs, GCD, cooldowns and rejection messages.']),
  feature('ability-impacts', 'Ability geometry and animation timing', 'both', 3, ['src/game/Combat.ts'], ['battlePrelateImpactTiming', 'playerAbilityEffects', 'abilityMovement'], ['Match melee/cone/area/projectile/beam coverage and damage at animation contact or projectile arrival.', 'Validate targeting/range/control before charging resources; blocked movement abilities spend nothing.']),
  feature('status-effects', 'Status, buff and recovery semantics', 'both', 3, ['src/game/abilities/abilityData.ts'], ['combatStatusEffects', 'abilityUtilitiesRuntime', 'resourceRegeneration'], ['Preserve damage-over-time, slow/root/silence/stagger, marks, shields, guard, empower, haste, stances and cleanse.', 'Preserve out-of-combat health regeneration and mana regeneration, death cancellation and full-pool recovery behavior.']),
  feature('enemy-ai', 'Enemy AI, telegraphs, corpses and respawn', 'both', 3, ['src/game/Enemy.ts'], ['combatEnemyAi', 'enemyTelegraphs'], ['Preserve raider/guard/caster/beast/captain profiles, aggro, pursuit, leash/home, caster distance and dodge windows.', 'Preserve interruption, death, corpse harvest, timed respawn and distinct training-dummy behavior.']),
  feature('keep-encounters', 'Local phased keep encounters', 'local', 3, ['src/game/KeepEncounter.ts'], ['keepEncounterRuntime', 'keepCommanderCombat', 'soloCommanderPacing'], ['Preserve prerequisite defenders, commander unlock, fight, defeat and secured phases.', 'Death/leaving resets active encounter correctly; quest field captains remain distinct.']),
  feature('progression', 'XP, levels, stats and gold', 'local', 3, ['src/services/local/characterLocal.ts'], ['characterLocal', 'abilityProgression'], ['Preserve kill/quest/capture/defense rewards, multilevel gains, stat growth and ability unlock notifications.', 'Level-up restores pools; character progression remains server-owned and isolated.']),
  feature('inventory', 'Inventory, item instances and equipment', 'local', 3, ['src/services/local/inventoryLocal.ts', 'src/data/items.ts'], ['inventoryCraftingQoL', 'runtimeEquippedAssembly'], ['Preserve 482 item definitions, 24 bag slots, 12 equipment slots, stack rules, affixes, consumables and stat recalculation.', 'Preserve search, filters, sorting, comparisons, sockets, fitted armor and body masking.']),
  feature('gathering', 'Corpse and world harvesting', 'local', 3, ['src/game/CraftingLogic.ts', 'src/services/local/craftingLocal.ts'], ['resourceNodes', 'resourceRegeneration'], ['Preserve scavenging humanoids, butchering beasts, node harvesting, profession ranks and persisted cooldowns.', 'Reject distance, skill, corpse-type and bag-capacity violations without spending or duplicating resources.']),
  feature('crafting', 'Salvage, cultivation, brewing and talismans', 'local', 3, ['src/data/crafting.ts', 'src/services/local/craftingLocal.ts'], ['inventoryCraftingQoL'], ['Preserve six professions, five recipes, two seeds, three growing plots, growth timers and optional soil bonus.', 'Preserve station/rank/material/space blockers, salvage unequipped items and recipe readiness/filtering.']),
  feature('quests', 'Both expedition quest chains', 'local', 3, ['src/data/quests.ts', 'src/game/QuestLogic.ts'], ['firstExpedition', 'questRewardCapacity', 'questNavigation'], ['Complete all eight quests; retain prerequisites, realm/level/location checks and kill counters.', 'Preserve acceptance/readiness/completion, marker/dialog/log state, affix rewards and capacity-safe turn-in.']),
  feature('campaign-objectives', 'Capture, defense and siege readiness', 'local', 4, ['src/services/local/campaignLocal.ts', 'src/data/campaign.ts'], ['campaignObjectiveLogic', 'campaignDefense', 'campaignStaticMaps'], ['Preserve hold/contest/influence behavior, objective prerequisites, keep rewards and defense cooldowns.', 'Require enemy T4 front, inner zone and fortress for city pressure; optional lairs never block campaign travel.']),
  feature('reward-settlement', 'Durable idempotent rewards', 'local', 4, ['src/game/CampaignRewards.ts'], ['campaignRewards', 'questRewardCapacity'], ['Deduplicate XP/gold/items across reconnects and retries.', 'Retain originally rolled pending gear when bags fill; later collection must not repay XP/gold.']),
  feature('world-content', 'All maps, services, resources and spawns', 'both', 5, ['src/world/ZoneLoader.ts', 'src/data/campaign.generated.ts'], ['campaignStaticMaps', 'expandedOrvrZones'], ['Preserve all 32 campaign zones and development-map fixture, objective IDs, props, NPCs, enemies, resources and stations.', 'Keep original Aegis/Riftbound identities and all authored transforms, scale, roads, water, lighting and districts.']),
  feature('travel', 'Portal travel and individual zone handoff', 'both', 4, ['src/game/Game.ts'], ['zoneTransition', 'zoneRouting'], ['Traverse all 70 directed campaign exits plus optional lairs; transfer only the entering player.', 'Preserve arrival grace, safe spawn/position, stale-activation rejection and character state without portal oscillation.']),
  feature('interiors', 'House and public-room interiors', 'local', 5, ['src/game/HouseInteriorRuntime.ts'], ['houseInteriorRuntime', 'houseInteriorGround'], ['Preserve enter/exit interactions, furnished rooms and suitably modeled residents.', 'Returning/logging out preserves exterior position rather than saving interior coordinates.']),
  feature('city-mechanisms', 'Doors, gates and passenger lifts', 'local', 5, ['src/world/CityLifts.ts'], ['cityLifts', 'citadelSiege', 'riftspireLayout'], ['Preserve calls/destinations, gates, passenger movement, colliders and floor height together.', 'Verify both capitals, citadel enclosure, stacked routes and interior return positions under server authority.']),
  feature('world-life', 'Ambient population, wildlife and effects', 'local', 5, ['src/world/WorldLife.ts'], ['worldLife', 'worldLifeContent', 'worldLifeMotion'], ['Preserve all ambient citizen/guard/wildlife placements and route/idle behavior with authored models.', 'Preserve smoke, embers, motes, flames and cloth without turning decorative actors into combat actors.']),
  feature('hud', 'HUD panels, prompts and feedback', 'both', 3, ['src/ui/hud/Hud.tsx'], ['playerQolD', 'objectiveHudData'], ['Preserve player/target frames, hotbar, statuses, nameplates, floating damage and interaction/error feedback.', 'Preserve draggable panels, close priority, objective/reward trackers and input isolation.']),
  feature('onboarding', 'First-session guidance', 'local', 3, ['src/ui/hud/Hud.tsx'], ['firstExpedition'], ['Preserve all eight guided tasks and their completion/progress state per character.']),
  feature('maps', 'Minimap and campaign atlas', 'local', 5, ['src/ui/hud/zoneMapGeometry.ts', 'src/world/mapZoneSource.ts'], ['zoneMapGeometry', 'mapZoneSource', 'campaignMapViewport', 'worldMapPresentation'], ['Preserve campaign/route/zone hierarchy, pan/zoom, layers, objective control, districts and floor awareness.', 'Show services/foes/resources/stations/exits/quest guidance; route to the correct destination and refresh GM edits without losing viewport.']),
  feature('wiki', 'Catalog-generated in-game guide', 'local', 5, ['src/wiki/wikiContent.ts'], ['wikiContent'], ['Retain six searchable sections and all catalog-generated pages with current gameplay values.']),
  feature('chat', 'Chat channels', 'local', 4, ['src/services/local/chatLocal.ts'], [], ['Provide server-routed say/zone/global/system channels with preserved visible behavior.', 'Authenticate sender identity and enforce channel membership and rate limits; client cannot forge system messages.']),
  feature('settings', 'Preferences and render/input settings', 'local', 5, ['src/state/gameStore.ts'], ['keybindings', 'renderResolution', 'foregroundFrameLoop'], ['Preserve FPS selection, render scaling, distance, sensitivities, inversion, key/mouse bindings and reset actions.', 'Persist local preferences; focus/background handling must not pause the dedicated server.']),
  feature('diagnostics', 'Performance and resource lifecycle', 'both', 6, ['src/game/Game.ts'], ['assetMemory', 'frameDiagnostics', 'renderWarmup'], ['Preserve developer diagnostics with accurate model/texture errors and rendered-frame timing.', 'Repeated transitions/load cancellation release resources; benchmark full battles and both capitals on all platforms.']),
  feature('gm-commands', 'Authenticated GM commands', 'local', 5, ['src/game/Game.ts'], ['gmCommands'], ['Preserve zone/coordinate/character teleport, ambiguity handling, spawn return, restore, cooldown reset, speed and flight.', 'Authorize every mutation server-side; ordinary players cannot grant themselves GM access.']),
  feature('gm-object-editor', 'Runtime object and prefab authoring', 'local', 5, ['src/world/editor/WorldEditorRuntime.ts'], ['builderEditing', 'builderCatalog', 'builderAssetPresentation'], ['Preserve select/move/rotate/scale/delete/restore, searchable grouped stamping, chain preview, grid/angle snapping and ruler.', 'Retain collision, walkable surfaces, identities and animation across all prefab replacements.']),
  feature('gm-terrain', 'Runtime voxel terrain authoring', 'local', 5, ['src/world/editor/WorldEditorRuntime.ts'], ['builderEditing', 'builderGroundSurface'], ['Preserve add/subtract/erase/smooth/flatten/roughen/paint and all six materials.', 'Rebuild validated server collision and map geometry; allowed terrain construction must not be removed by the primitive-model ban.']),
  feature('gm-publication', 'Drafts, versioning and restore', 'local', 5, ['src/services/local/worldEditLocal.ts'], ['builderEditing', 'mapZoneSource'], ['Preserve undo/redo, autosave/drafts, validation, notes, published versions and reset-to-live.', 'Publish authorized changes atomically and retain rollback; map and collision consumers share one version.']),
  feature('online-identity', 'Steam identity and character ownership', 'shared', 4, ['server/auth.ts'], ['orvrAuthority', 'orvrDatabase'], ['Verify Steam ownership server-side before issuing short-lived sessions.', 'Preserve immutable realm, owned characters, one active character/account and complete roster creation.']),
  feature('admission-reconnect', 'Realm queues and reconnect', 'shared', 4, ['server/authority.ts', 'src/shared/orvr/protocol.ts'], ['orvrConnection', 'orvrAuthority'], ['Enforce 18/realm/contested zone, overflow queue and staging admission.', 'Resume owned position/sequence; reject stale commands without duplicate avatars; carry cooldowns/status across zone clocks.']),
  feature('shared-combat', 'Authoritative replicated combat', 'shared', 4, ['src/shared/orvr/simulation.ts', 'server/abilityCatalog.ts'], ['orvrAbilities', 'orvrSimulation'], ['Server validates movement, targeting, range, realm, resource costs, effects, NPC attacks and death/respawn.', 'Prediction/reconciliation preserves rules under latency/loss; only Unreal owns live combat after cutover.']),
  feature('supplies', 'Supply production and caravans', 'shared', 4, ['src/shared/orvr/simulation.ts'], ['orvrSimulation', 'orvrRoadNetwork', 'campaignCaravanPresentation'], ['Preserve production, dispatch, physical routes, escorts, attack/delivery and spending.', 'Retain articulated vehicles, creatures, cargo and complex operator models with meaningful fitting/animation.']),
  feature('siege', 'Keep development and siege operations', 'shared', 4, ['src/shared/orvr/equipment.ts', 'src/shared/orvr/simulation.ts'], ['orvrSiegeOperations', 'orvrRamCrew', 'orvrEquipmentOperator'], ['Preserve upgrades, purchases, equipment operation, fitted crew, ammunition, repair, gate breach, commander defeat and keep capture.', 'Preserve defender posterns, oil/cauldron access and collision-correct equipment placement.']),
  feature('campaign-rounds', 'Front transitions, city siege and reset', 'shared', 4, ['src/shared/orvr/simulation.ts', 'src/shared/orvr/config.ts'], ['orvrSimulation', 'orvrConfigCompatibility'], ['Preserve advancing fronts, counterpush, central breakthrough, city objective order, attacker/defender timeout and result.', 'Pause empty-city timer; reset next round while retaining defined history/contributions and exploration access.']),
  feature('persistence', 'Durable checkpoints, journals and recovery', 'shared', 4, ['server/persistence.ts', 'server/configCompatibility.ts'], ['orvrDatabase', 'orvrDatabaseAudit', 'orvrConfigCompatibility'], ['Commit durable mutations before acknowledgement; deduplicate retries and enforce revision/ownership leases.', 'Failure restores durable state and pauses unsafe mutation; reject incompatible content without erasing saves.']),
  feature('production-operations', 'Cross-platform release and operations', 'both', 6, ['server/README.md'], ['orvrServerAudit'], ['Verify Windows/Linux/macOS packaged clients with Linux servers, Steam tickets, revocation, deployment and patch compatibility.', 'Exercise backups/restore, crash recovery, simultaneous fronts, clean installs, monitoring and documented performance budgets.']),
];

export function validateParityLedger(root = repoRoot): string[] {
  const errors: string[] = [];
  const ids = new Set<string>();
  for (const entry of parityFeatures) {
    if (ids.has(entry.id)) errors.push(`Duplicate parity ID: ${entry.id}`);
    ids.add(entry.id);
    if (!entry.acceptance.length || !entry.sourceFiles.length) errors.push(`Incomplete behavior contract: ${entry.id}`);
    for (const file of [...entry.sourceFiles, ...entry.referenceTests]) {
      if (!existsSync(path.join(root, file))) errors.push(`${entry.id}: missing evidence source ${file}`);
    }
  }
  return errors;
}
