export interface ClassGuide {
  summary: string;
  opener: string[];
  singleTarget: string[];
  area: string[];
  resourceRule: string;
  priorities: string[];
}

export const CLASS_GUIDES: Record<string, ClassGuide> = {
  'Ember Arcanist': {
    summary: 'Build Heat safely, prime the target, then spend on the beam before cashing out with the meteor.',
    opener: ['Furnace Heart', 'Kindle Hex', 'Spark Lash', 'Spark Lash', 'Spark Lash', 'Ashen Cataclysm'],
    singleTarget: ['Kindle Hex', 'Spark Lash', 'Ashen Cataclysm', 'Cinder Lance'],
    area: ['Furnace Heart', 'Pyre Circle', 'Kindle Hex', 'Phoenix Collapse'],
    resourceRule: 'Hold Phoenix Collapse for full Heat; use Ashen Cataclysm at 35 Heat or more.',
    priorities: ['Use White Cautery only when survival requires it.', 'Use Flashstep to escape or scorch a line, not as a damage-only button.'],
  },
  'Hex Inquisitor': {
    summary: 'Apply the anoint and marks, build Verdicts with ranged and melee attacks, then execute wounded targets.',
    opener: ['Relic Oil', 'Brand Shot', 'Interrogate', 'Silver Snare', 'Purging Slash'],
    singleTarget: ['Brand Shot', 'Interrogate', 'Purging Slash', 'Stake the Guilty'],
    area: ['Relic Oil', 'Torch of Scorn', 'Silver Snare', 'Purging Slash'],
    resourceRule: 'Build to five Verdicts before Final Sentence; spend two on Purging Slash and three on Stake the Guilty.',
    priorities: ['Use Stake the Guilty against wounded targets.', 'Use Ash Ward for cleanses or incoming magic instead of delaying it for damage.'],
  },
  'Sunfire Templar': {
    summary: 'Choose the aura for the situation, mark the target, control the pull, and sweep when Valor is ready.',
    opener: ['Solar Edict', 'Banner Rush', 'Sunbrand Strike', 'Rallying Rebuke', 'Radiant Counter', 'Heavenrend Sweep'],
    singleTarget: ['Sunbrand Strike', 'Rallying Rebuke', 'Radiant Counter', 'Heavenrend Sweep'],
    area: ['Solar Edict', 'Banner Rush', 'Rallying Rebuke', 'Heavenrend Sweep', 'Daybreak Standard'],
    resourceRule: 'Keep enough Valor for Heavenrend Sweep; switch to Bastion Edict for pressure and Pursuit Edict for travel or chase.',
    priorities: ['Keep threat and damage reduction ahead of personal damage.', 'Use Shield of Noon before predictable frontal bursts.'],
  },
  'Battle Prelate': {
    summary: 'Stay in melee to build Zeal, convert it through empowered strikes, and turn the fight into healing when allies are pressured.',
    opener: ['Hymn of Resolve', 'Penance Step', 'Litany of Strikes', 'Sanctified Blow', 'Reliquary Smash', 'Icon of Wrath'],
    singleTarget: ['Litany of Strikes', 'Sanctified Blow', 'Judgment of Ash', 'Redemption Surge'],
    area: ['Hymn of Resolve', 'Penance Step', 'Reliquary Smash', 'Icon of Wrath', 'Last Homily'],
    resourceRule: 'Use Redemption Surge at 35 Zeal when health is low; hold Last Homily for a full group damage-to-healing window.',
    priorities: ['Martyr’s Ward takes priority over damage when an ally is threatened.', 'Keep Icon of Wrath under the active melee group.'],
  },
  Stoneguard: {
    summary: 'Bind the oath, establish Grudge and control, then turn blocked pressure into retaliatory damage.',
    opener: ['Oath Bind', 'Grudge Axes', 'Vengeful Hook', 'Clanwall', 'Runebound Mail', 'Holdfast'],
    singleTarget: ['Grudge Axes', 'Vengeful Hook', 'Clanwall', 'Bitter Reprisal'],
    area: ['Grudge Axes', 'Clanwall', 'Holdfast', 'Book of Wrongs'],
    resourceRule: 'Spend Grudge on Bitter Reprisal after establishing pressure; use Hearthguard Vow for ally protection or cleanse.',
    priorities: ['Keep Holdfast or Runebound Mail active during sustained hits.', 'Use Vengeful Hook to keep priority targets in your control range.'],
  },
  Doomseeker: {
    summary: 'Enter the berserk state, apply bleed, then alternate fast builders and rage dumps before the vulnerability crash.',
    opener: ['Death Oath', 'Bloodhowl', 'Skullsplit Leap', 'Twin Hew', 'Reckless Arc', 'No Respite'],
    singleTarget: ['Twin Hew', 'Skullsplit Leap', 'No Respite', 'Exhausting Swing'],
    area: ['Death Oath', 'Bloodhowl', 'Reckless Arc', 'Doom Roar', 'Final Reckoning'],
    resourceRule: 'Use No Respite on bleeding targets and Exhausting Swing when Rage is high; do not empty Rage before the burst window.',
    priorities: ['Use Grim Pursuit to stay on targets through slows.', 'Use Doom Roar to prevent peel before committing to the finisher.'],
  },
  Glyphbinder: {
    summary: 'Layer marks and rune zones, then refresh the whole field with the ancestral ultimate.',
    opener: ['Oath Script', 'Rune of Cleaving', 'Anchor Sigil', 'Master Rune of Hearth', 'Master Rune of Ruin', 'Stoneword'],
    singleTarget: ['Rune of Cleaving', 'Stoneword', 'Master Rune of Ruin', 'Ancestor’s Favor'],
    area: ['Anchor Sigil', 'Master Rune of Hearth', 'Master Rune of Ruin', 'Stoneword', 'Ancestor Lexicon'],
    resourceRule: 'Spend Runic Focus after the key runes are active; use Ancestor’s Favor at 25 focus when cleanse or healing is needed.',
    priorities: ['Keep Rune of Warding on the threatened ally.', 'Place Anchor Sigil where enemies must cross rather than under the current target.'],
  },
  Siegewright: {
    summary: 'Deploy first, overclock the emplacement, then combine traps and artillery while keeping enemies in the firing lane.',
    opener: ['Deploy Gunlet', 'Crank Charge', 'Landmine Satchel', 'Harpoon Line', 'Fragment Bomb', 'Ironstorm Battery'],
    singleTarget: ['Deploy Gunlet', 'Crank Charge', 'Harpoon Line', 'Armor Piercer', 'Ironstorm Battery'],
    area: ['Deploy Gunlet', 'Landmine Satchel', 'Fragment Bomb', 'Ironstorm Battery', 'Fortified Redoubt'],
    resourceRule: 'Build Pressure with Crank Charge and spend it on Armor Piercer or Ironstorm Battery; reserve the ultimate for a set emplacement.',
    priorities: ['Use Grapnel Traverse for safety or a better firing angle.', 'Use Buckshot Salvo when enemies breach the turret line.'],
  },
  'Blade Savant': {
    summary: 'Follow the stance chain in order: step, opening, rising, then the Perfect Form finisher.',
    opener: ['Enchanted Edge', 'Moonstep', 'Opening Form', 'Rising Form', 'Perfect Form'],
    singleTarget: ['Moonstep', 'Opening Form', 'Rising Form', 'Perfect Form'],
    area: ['Enchanted Edge', 'Spiral Guard', 'Opening Form', 'Rising Form', 'Sevenfold Kata'],
    resourceRule: 'Do not spend Balance early; preserve the chain so Perfect Form lands after Opening and Rising Form.',
    priorities: ['Use Warding Arc against frontal attacks.', 'Use Mindward before predictable spell bursts or to protect the party.'],
  },
  'Pride Warden': {
    summary: 'Mark prey, synchronize with the companion, then spend Pack Fury on the paired knockdown and cleave.',
    opener: ["Hunter’s Mark", 'Pounce', "Flanker’s Path", 'Pack Rend', 'Snare Net'],
    singleTarget: ["Hunter’s Mark", 'Pack Rend', "King’s Leap", 'Trophy Axe'],
    area: ['Guardian Roar', 'Pounce', 'Pack Rend', 'Trophy Axe', 'Pride Unleashed'],
    resourceRule: 'Build Pack Fury through the marked target and spend it on King’s Leap or Trophy Axe; hold Pride Unleashed for the hunt phase.',
    priorities: ['Use Wild Bond to stabilize both hunter and beast.', 'Use Guardian Roar when the companion must peel instead of chase.'],
  },
  'Aether Sage': {
    summary: 'Alternate damage and healing polarity, convert the echo through Energy Weave, then double the strongest follow-up.',
    opener: ['Starshard', 'Verdant Current', 'Energy Weave', 'Moonwell', 'Sunpierce'],
    singleTarget: ['Starshard', 'Verdant Current', 'High Concord', 'Sunpierce'],
    area: ['Moonwell', 'Comet Snare', 'High Concord', 'Sunpierce', 'Celestial Equinox'],
    resourceRule: 'Alternate Starshard and Verdant Current to build High Magic; use High Concord before the strongest opposite-polarity spell.',
    priorities: ['Use Merciful Veil before emergency healing is required.', 'Use Tranquil Drift to preserve casting position, not to chase damage.'],
  },
  'Veil Ranger': {
    summary: 'Mark the target, fire from range, and reserve movement tools for disengage or a confirmed finishing window.',
    opener: ['Vengeance Mark', 'Longdraw', 'Running Shot', 'Moonshot'],
    singleTarget: ['Vengeance Mark', 'Longdraw', 'Running Shot', 'Moonshot'],
    area: ['Waylay Trap', 'Barbed Volley', 'Running Shot', 'Eclipse Hunt'],
    resourceRule: 'Maintain Focus through consistent shots; use Eclipse Hunt when the target is marked and escape routes are limited.',
    priorities: ['Use Eye Pierce to interrupt instead of delaying it for damage.', 'Use Mist Walk or Shadow Rush to control distance.'],
  },
  Dreadsworn: {
    summary: 'Select the aura package for the encounter, spread curse pressure, and stay in the center of the disruption.',
    opener: ['Aura of Ruin', 'Hexbrand Cleave', "Tyrant’s Advance", 'Sunder Faith', 'Black Bastion', 'Harrowing Roar'],
    singleTarget: ['Aura of Ruin', 'Hexbrand Cleave', 'Sunder Faith', 'Warp Riposte', 'Harrowing Roar'],
    area: ['Aura of Ruin', 'Aura of Dominion', 'Hexbrand Cleave', 'Harrowing Roar', 'Crown of Ruin'],
    resourceRule: 'Dark Gifts are spent to maintain the correct aura and defensive state; use Crown of Ruin after all three auras are established.',
    priorities: ['Use Aura of Dread against enemy burst and Aura of Dominion against control-heavy groups.', 'Use Black Bastion before blocking a committed attack.'],
  },
  'Warped Reaver': {
    summary: 'Choose the mutation form for the problem, pull the target into rupture range, then cash out the empowered form.',
    opener: ['Mutate Crusher', 'Flesh Hook', 'Bone Splinter', 'Mutation Shift', 'Ravage Burst'],
    singleTarget: ['Mutate Crusher', 'Flesh Hook', 'Mutation Shift', 'Ravage Burst'],
    area: ['Mutate Claw', 'Warpsprint', 'Bone Splinter', 'Ravage Burst', 'Apotheosis of Change'],
    resourceRule: 'Use Crusher for armor break, Claw for chase pressure, and Tendril for reach or pull; spend Mutation after the form is correct.',
    priorities: ['Use Hideous Regrowth before dropping into lethal range.', 'Use Warpsprint to force contact, not as a late escape after the form expires.'],
  },
  'Void Magister': {
    summary: 'Build the encounter around the idol: debuff, pull enemies into fields, then unleash the storm and conjunction.',
    opener: ['Summon Idol', 'Feed the Idol', 'Unmake Armor', 'Entropic Field', 'Rift Pull', 'Daemonfire Orb'],
    singleTarget: ['Summon Idol', 'Unmake Armor', 'Daemonfire Orb', 'Warp Storm'],
    area: ['Summon Idol', 'Entropic Field', 'Rift Pull', 'Warp Storm', 'Grand Conjunction'],
    resourceRule: 'Keep the idol active before spending Warp Charge; use Warp Storm at 30 charge and Grand Conjunction for the layered burst.',
    priorities: ['Use Hover Disc to kite without abandoning the idol zone.', 'Feed the Idol is an investment button; do not use it while already resource-starved.'],
  },
  'Ruin Oracle': {
    summary: 'Mark allies and enemies, siphon through the harbinger, and detonate the affliction after the cursed ground is established.',
    opener: ['Mark of Vigor', 'Harbinger of Frailty', 'Tether of Agony', 'Soul Drain Rite', 'Scourging Sigil'],
    singleTarget: ['Harbinger of Frailty', 'Tether of Agony', 'Soul Drain Rite', 'Prophecy of Ash'],
    area: ['Fetish Ward', 'Madness Cant', 'Scourging Sigil', 'Prophecy of Ash', 'Altar of the Raven'],
    resourceRule: 'Spend Dark Gifts on Prophecy of Ash after the debuffs are active; reserve Altar of the Raven for a fully marked group.',
    priorities: ['Keep Blessing of Ruin available for life-saving wards.', 'Use Fetish Ward before a cleanse is needed rather than after the first debuff lands.'],
  },
  Warbrute: {
    summary: 'Advance the Plan with the two builders, then cash out at the highest tier while keeping the brawl controlled.',
    opener: ['Sneaky Start', 'Proper Wallop', 'Boss Stomp', "Wot’s Yours Is Mine", 'Biggest Finish'],
    singleTarget: ['Sneaky Start', 'Proper Wallop', 'Biggest Finish'],
    area: ['Get Stuck In', 'Boss Stomp', 'Proper Wallop', "Boss’s Big Idea"],
    resourceRule: 'Never spend Biggest Finish before the top Plan tier unless the target will escape; use defensive shouts between builder casts.',
    priorities: ['Use Shut It! to stop dangerous casts.', 'Use You Watch Me! when protecting an ally is more valuable than another builder.'],
  },
  'Fang Herder': {
    summary: 'Select the companion stance, send the beast first, then stack ranged pressure before the heavy companion leap.',
    opener: ['Hound Fang', 'Loose Fang', 'Skewa Shot', 'Bait Bag', 'Needle Rain'],
    singleTarget: ['Loose Fang', 'Skewa Shot', 'Big Chompa', 'Gobbo Prod'],
    area: ['Spit Fang', 'Bait Bag', 'Needle Rain', 'Big Chompa', 'Fang Stampede'],
    resourceRule: 'Choose Hound Fang for chase or Spit Fang for poison pressure; spend Pack Fury on Big Chompa and preserve the stampede for a lane.',
    priorities: ['Use Bouncin’ Escape when the pet is safe and you need distance.', 'Use Gobbo Prod during the companion’s committed attack window.'],
  },
  'Bog Hexer': {
    summary: 'Alternate offensive and healing builders, then echo the chosen polarity through the beam and concoction.',
    opener: ['Mixed Medicine', 'Green Zap', 'Patch-Up', 'Sticky Curse', 'Crooked Beam', 'Foul Brew'],
    singleTarget: ['Green Zap', 'Patch-Up', 'Sticky Curse', 'Crooked Beam'],
    area: ['Mixed Medicine', 'Sticky Curse', 'Foul Brew', 'Brain Banga', 'Big Green Turnabout'],
    resourceRule: 'Alternate Green Zap and Patch-Up to build support power and hex power; use Mixed Medicine before the most valuable echo.',
    priorities: ['Use Brain Banga to interrupt priority casts.', 'Use Lucky Idol when the group can remain near its healing field.'],
  },
  Cleaver: {
    summary: 'Keep the attack tempo running, drag enemies into the pack, and dump Rage only after bleed and positioning are established.',
    opener: ['Keep Swingin', "Get Over ’Ere", 'Deep Cutz', 'Whirly Chop', 'Smash Pile'],
    singleTarget: ['Mad Dash', "Get Over ’Ere", 'Deep Cutz', 'Facebreaker', 'Heavy Chop'],
    area: ['Mad Dash', 'Smash Pile', 'Deep Cutz', 'Whirly Chop', 'Red Mist'],
    resourceRule: 'Build Rage with Whirly Chop and maintain pressure; use Heavy Chop or Red Mist only after the group is committed.',
    priorities: ['Use Can’t Stop Me against control-heavy enemies.', 'Use Facebreaker to interrupt or secure the heavy chop.'],
  },
  'Blood Dancer': {
    summary: 'Open from stealth, apply both blood effects, then detonate poison before executing the marked prey.',
    opener: ['Shadow Prowl', 'Vein Slice', 'Poison Kiss', 'Heartseeker', 'Razor Waltz', 'Suffering Bloom'],
    singleTarget: ['Vein Slice', 'Poison Kiss', 'Razor Waltz', 'Suffering Bloom', 'Red Caress'],
    area: ['Shadow Prowl', 'Heartseeker', 'Suffering Bloom', 'Crimson Ecstasy'],
    resourceRule: 'Build Bloodlust with both openers, spend two on Suffering Bloom, then three on Red Caress; hold the ultimate for the flank.',
    priorities: ['Use Mirror Veil to survive the commit.', 'Use Crippling Cut when healing reduction or slow matters more than another flurry.'],
  },
  'Dread Guard': {
    summary: 'Mark the prey, pull it into the cage, disrupt its defense, and convert Hatred into sustain.',
    opener: ['Malice Guard', 'Spite Lash', 'Glaive Hook', 'Sunder Grace', 'Torment Cage'],
    singleTarget: ['Malice Guard', 'Spite Lash', 'Sunder Grace', 'Harrow Pike', 'Bitter Harvest'],
    area: ['Cruel Intercept', 'Glaive Hook', 'Torment Cage', 'Harrow Pike', "Throne’s Contempt"],
    resourceRule: 'Build Hatred on the marked target and spend it on Bitter Harvest after the debuff chain is active.',
    priorities: ['Use Void Buckler for spell block and reflect windows.', 'Use Cruel Intercept to protect allies or prevent escape.'],
  },
  'Dusk Weaver': {
    summary: 'Layer the critical-harm debuff and root, then release Dark Power through the ground storm and backlash.',
    opener: ['Agony Thread', 'Chill of Dusk', 'Soul Freeze', 'Black Shard', 'Void Rain'],
    singleTarget: ['Umbral Bolt', 'Agony Thread', 'Soul Freeze', 'Black Shard', 'Backlash Surge'],
    area: ['Chill of Dusk', 'Void Rain', 'Soul Freeze', 'Backlash Surge', 'Midnight Cataclysm'],
    resourceRule: 'Use Cruel Harvest at 25 Dark Power for safety or setup; hold Backlash Surge until the target is controlled.',
    priorities: ['Use Gloom Step to leave a curse pool while repositioning.', 'Do not spend Soul Freeze after the target has already used its escape.'],
  },
  'Crimson Acolyte': {
    summary: 'Maintain the lifesteal aura, mark the victim, then use the knife spin to turn damage into group sustain.',
    opener: ['Razor Prayer', 'Pain Mirror', 'Siphon Cut', 'Cruel Embrace', 'Borrowed Vigor', 'Covenant of Knives'],
    singleTarget: ['Pain Mirror', 'Siphon Cut', 'Cruel Embrace', 'Borrowed Vigor', 'Covenant of Knives'],
    area: ['Razor Prayer', 'Cruel Embrace', 'Covenant of Knives', 'Dark Communion', 'Feast of the Shrine'],
    resourceRule: 'Build Essence with Siphon Cut and Pain Mirror; spend it on Blood Rite or Dark Communion only after the damage window is active.',
    priorities: ['Use Blood Rite for immediate emergency healing and Dark Communion for a planned group recovery.', 'Use Scarlet Step to keep the lifesteal zone connected to the fight.'],
  },
};

export function getClassGuide(className: string): ClassGuide | null {
  return CLASS_GUIDES[className] ?? null;
}
