"""Audit the actual LOD0 GLBs in a disposable, clean Blender scene.

No geometry or animations are corrected here. Rest matrices are compared both
through the binary inverse bind matrices and through Blender's reimport. Contact
is measured at quarter-frame intervals. BVH overlap candidates and clearances
are diagnostics for targeted visual review, never a collision-clear certificate.
"""
from __future__ import annotations

import argparse
import bisect
from contextlib import contextmanager
from datetime import datetime, timezone
import hashlib
import json
import math
from pathlib import Path
import sys

import bpy
import numpy as np
from mathutils import Matrix, Quaternion, Vector
from mathutils.bvhtree import BVHTree

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/"tools"))
import reimport_review as review
from validate_runtime import Glb, skin_signatures

review.bpy=bpy
review.Matrix=Matrix
CLIPS=review.CLIPS
EXPECTED_RANGES={"idle":(0,48),"walk":(0,24),"run":(0,16),"combat_idle":(0,64),
                 "attack_melee":(0,24),"attack_ranged":(0,32),"cast":(0,48),"death":(0,48),"jump":(0,32)}
PAIRS=(("hands","chest"),("hands","shoulders"),("head","shoulders"),("hands","waist"),
       ("legs","feet"),("legs","tabard"),("back","shoulders"))
SUPPLEMENTAL_LATE_DEATH_CAMERA={"id":"supplemental_late_death_wide",
    "position":[3,-5.05,.40],"target":[0,-.05,.40],
    "orthographic_scale":3.2,"resolution":[1500,850]}
_IMPORT_GLB=review.import_glb
_IGNORED_BONE_DISPLAYS=[]


def _import_without_bone_displays(path):
    imported=_IMPORT_GLB(path)
    displays={bone.custom_shape for obj in imported if obj.type=="ARMATURE" for bone in obj.pose.bones if bone.custom_shape}
    for obj in displays & imported:
        # These are generated by Blender's importer, absent from the GLB mesh
        # list, and referenced only as armature UI display shapes.
        obj.hide_render=True
        obj.hide_set(True)
        _IGNORED_BONE_DISPLAYS.append({"source":path.name,"object":obj.name,"reason":"Armature bone custom_shape display"})
    return imported-displays


review.import_glb=_import_without_bone_displays


def _digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def _matrix_delta(left,right):
    return max(abs(left[row][col]-right[row][col]) for row in range(4) for col in range(4))


def _column_matrix(values):
    return Matrix([values[index:index+4] for index in range(0,16,4)]).transposed()


def _node_matrix(node):
    if "matrix" in node:
        return _column_matrix(node["matrix"])
    rotation=node.get("rotation",[0,0,0,1])
    return Matrix.LocRotScale(Vector(node.get("translation",[0,0,0])),
                             Quaternion((rotation[3],*rotation[:3])),Vector(node.get("scale",[1,1,1])))


def _world_matrices(document):
    nodes=document["nodes"]
    parents={child:parent for parent,node in enumerate(nodes) for child in node.get("children",[])}
    worlds={}
    def world(index):
        if index not in worlds:
            local=_node_matrix(nodes[index])
            worlds[index]=world(parents[index]) @ local if index in parents else local
        return worlds[index]
    return {index:world(index) for index in range(len(nodes))}


def binary_animation_and_rest(body_path,reference,fps):
    glb=Glb(body_path.read_bytes(),body_path)
    signatures=skin_signatures(glb)
    if len(signatures)!=1:
        raise ValueError("Body must have exactly one canonical skin")
    joints=signatures[0]["joints"]
    names=set(reference["bones"])
    errors=[]
    if set(joints)!=names:
        errors.append("Binary skin joint names differ from the frozen 56-bone contract")
    conversion=Matrix.Rotation(math.pi/2,4,"X")
    worlds=_world_matrices(glb.document)
    nodes=glb.document["nodes"]
    node_lookup={node.get("name"):index for index,node in enumerate(nodes)}
    bone_records={}
    for name in sorted(names & set(joints)):
        expected=Matrix(reference["bones"][name]["matrix"])
        inverse_bind=_column_matrix(joints[name]["inverse_bind"])
        bind_world=conversion @ inverse_bind.inverted()
        node_world=conversion @ worlds[node_lookup[name]]
        bone_records[name]={"inverse_bind_rest_delta":_matrix_delta(bind_world,expected),
                            "node_rest_delta":_matrix_delta(node_world,expected)}
    maximum_bind=max((item["inverse_bind_rest_delta"] for item in bone_records.values()),default=float("inf"))
    maximum_node=max((item["node_rest_delta"] for item in bone_records.values()),default=float("inf"))
    if maximum_bind>1e-5 or maximum_node>1e-5:
        errors.append(f"Canonical binary rest matrices changed: inverse bind {maximum_bind:.8g}, node {maximum_node:.8g}")
    animations={}
    for action in glb.document.get("animations",[]):
        channels=[]
        minimum=float("inf")
        maximum=float("-inf")
        for channel in action["channels"]:
            sampler=action["samplers"][channel["sampler"]]
            times=[row[0] for row in glb.accessor(sampler["input"])["rows"]]
            values=glb.accessor(sampler["output"])["rows"]
            if not all(math.isfinite(v) for row in values for v in row):
                errors.append(f"Nonfinite animation values: {action['name']}")
            if any(left>=right for left,right in zip(times,times[1:])):
                errors.append(f"Nonincreasing animation times: {action['name']}")
            minimum=min(minimum,min(times))
            maximum=max(maximum,max(times))
            frames=[time*fps for time in times]
            channels.append({"node":nodes[channel["target"]["node"]].get("name"),
                "path":channel["target"]["path"],"interpolation":sampler.get("interpolation","LINEAR"),
                "key_count":len(times),"fractional_frame_key_count":sum(abs(frame-round(frame))>1e-4 for frame in frames),
                "minimum_seconds":min(times),"maximum_seconds":max(times)})
        animations[action["name"]]={"channels":channels,"duration_seconds":maximum-minimum,
                                     "minimum_seconds":minimum,"maximum_seconds":maximum,
                                     "fractional_rotation_keys":sum(c["fractional_frame_key_count"] for c in channels if c["path"]=="rotation")}
        if action["name"] in EXPECTED_RANGES:
            first,last=EXPECTED_RANGES[action["name"]]
            if abs((maximum-minimum)-(last-first)/fps)>1e-5:
                errors.append(f"Clip duration changed: {action['name']}")
    if set(animations)!=set(CLIPS):
        errors.append("Exported animation names differ from the nine canonical clips")
    melee_channels=animations.get("attack_melee",{}).get("channels",[])
    for side in ("R","L"):
        for part in ("upper_arm","forearm","hand"):
            name=f"{part}_{side}"
            channel=next((value for value in melee_channels if value["node"]==name and value["path"]=="rotation"),None)
            if channel is None or channel["key_count"]<49 or channel["fractional_frame_key_count"]<24:
                errors.append(f"Melee half-frame rotation keys were discarded or incomplete: {name}")
    return {"body_sha256":_digest(body_path),"fps":fps,"bone_count":len(joints),"bones":bone_records,
            "maximum_inverse_bind_rest_delta":maximum_bind,"maximum_node_rest_delta":maximum_node,
            "animations":animations,"errors":errors}


def reimport_rest(assembly,reference):
    rig=assembly["rig"]
    names=set(reference["bones"])
    records={name:_matrix_delta(rig.data.bones[name].matrix_local,Matrix(reference["bones"][name]["matrix"]))
             for name in names if name in rig.data.bones}
    maximum=max(records.values(),default=float("inf"))
    return {"bone_count":len(rig.data.bones),"maximum_matrix_delta":maximum,"per_bone_delta":records,
            "armature_world_matrix_delta":_matrix_delta(rig.matrix_world,Matrix(reference["matrix_world"])),
            "passed":len(records)==len(names) and maximum<=1e-5}


def _weapon_marker_owner(assembly):
    candidates=[obj for obj in assembly["weapon"] if all(key in obj for key in
                ("primary_grip_local","secondary_grip_local","head_center_local"))]
    if len(candidates)!=1:
        raise ValueError(f"Expected one exported hammer marker owner, found {len(candidates)}")
    return candidates[0]


def _marker_world(owner,key):
    # Blender's importer converts mesh vertices and object transforms back to
    # Blender coordinates. Extras were exported verbatim in that same authored
    # basis; applying a second Y-up conversion here would rotate the marker away
    # from the real shaft.
    return owner.matrix_world @ Vector(owner[key])


def _joint_metrics(rig):
    metrics={}
    for side in ("R","L"):
        upper=rig.pose.bones[f"upper_arm_{side}"]
        fore=rig.pose.bones[f"forearm_{side}"]
        hand=rig.pose.bones[f"hand_{side}"]
        thigh=rig.pose.bones[f"thigh_{side}"]
        shin=rig.pose.bones[f"shin_{side}"]
        metrics[f"elbow_{side}_degrees"]=math.degrees((upper.tail-upper.head).angle(fore.tail-fore.head))
        metrics[f"wrist_{side}_degrees"]=math.degrees((fore.tail-fore.head).angle(hand.tail-hand.head))
        metrics[f"knee_{side}_degrees"]=math.degrees((thigh.tail-thigh.head).angle(shin.tail-shin.head))
    return metrics


def grip_audit(assembly):
    owner=_weapon_marker_owner(assembly)
    records={}
    for name in ("combat_idle","attack_melee"):
        action=assembly["actions"][name]
        first,last=action.frame_range
        samples=[]
        for index in range(round((last-first)*4)+1):
            fraction=index/((last-first)*4)
            frame=review.set_clip(assembly,name,fraction)
            primary=_marker_world(owner,"primary_grip_local")
            secondary=_marker_world(owner,"secondary_grip_local")
            head=_marker_world(owner,"head_center_local")
            right=assembly["sockets"]["socket_hand_R"].matrix_world.translation
            left=assembly["sockets"]["socket_hand_L"].matrix_world.translation
            samples.append({"frame":frame,"fraction":fraction,
                "primary_gap_m":(right-primary).length,"secondary_gap_m":(left-secondary).length,
                "primary_world":list(primary),"secondary_world":list(secondary),"head_world":list(head),
                "joints":_joint_metrics(assembly["rig"])})
        worst=max(samples,key=lambda record:record["secondary_gap_m"])
        records[name]={"sample_count":len(samples),"maximum_secondary_gap_m":worst["secondary_gap_m"],
                       "worst_frame":worst["frame"],"worst_fraction":worst["fraction"],
                       "maximum_primary_gap_m":max(s["primary_gap_m"] for s in samples),
                       "maximum_wrist_bend_degrees":max(s["joints"][f"wrist_{side}_degrees"] for s in samples for side in ("R","L")),
                       "samples":samples}
    return records


@contextmanager
def game_playback(assembly):
    """Match Player.sanitizePlayerAnimationClip: drop root and all scale tracks."""
    states=[]
    for action in assembly["actions"].values():
        for layer in action.layers:
            for strip in layer.strips:
                for bag in strip.channelbags:
                    for curve in bag.fcurves:
                        if 'pose.bones["root"]' in curve.data_path or curve.data_path=="scale" or curve.data_path.endswith(".scale"):
                            states.append((curve,curve.mute))
                            curve.mute=True
    try:
        yield len(states)
    finally:
        for curve,value in states:
            curve.mute=value
        review.rest_pose(assembly)


def support_audit(assembly):
    boots=[obj for obj in assembly["all_meshes"] if obj.get("reimport_module")=="feet"]
    if not boots:
        raise ValueError("Actual exported boots are missing from support audit")
    records={}
    for name in CLIPS:
        action=assembly["actions"][name]
        first,last=action.frame_range
        rate=16 if name=="walk" else 8
        samples=[]
        for index in range(round((last-first)*rate)+1):
            fraction=index/((last-first)*rate)
            frame=review.set_clip(assembly,name,fraction)
            minimum=float("inf")
            depsgraph=bpy.context.evaluated_depsgraph_get()
            for obj in boots:
                evaluated=obj.evaluated_get(depsgraph)
                mesh=evaluated.to_mesh()
                try:
                    minimum=min(minimum,min((evaluated.matrix_world @ vertex.co).z for vertex in mesh.vertices))
                finally:
                    evaluated.to_mesh_clear()
            samples.append({"frame":frame,"fraction":fraction,"boot_minimum_z_m":minimum})
        worst=min(samples,key=lambda item:item["boot_minimum_z_m"])
        highest=max(samples,key=lambda item:item["boot_minimum_z_m"])
        records[name]={"sample_count":len(samples),"minimum_support_z_m":worst["boot_minimum_z_m"],
                       "maximum_support_z_m":highest["boot_minimum_z_m"],"lowest_frame":worst["frame"],
                       "highest_frame":highest["frame"],"positive_airborne_clearance_allowed":name in {"run","jump"},"samples":samples}
        print("GAME_SUPPORT_SAMPLED",name,records[name]["minimum_support_z_m"],records[name]["maximum_support_z_m"],flush=True)
    return records


def _module_geometry(assembly):
    groups={slot:[] for slot in review.SLOTS}
    for obj in assembly["all_meshes"]:
        slot="body" if obj in assembly["meshes"] else obj.get("reimport_module")
        if slot not in groups:
            raise ValueError(f"Cannot classify imported object {obj.name}")
        groups[slot].append(obj)
    result={}
    depsgraph=bpy.context.evaluated_depsgraph_get()
    for slot,objects in groups.items():
        vertices=[]
        triangles=[]
        for obj in objects:
            evaluated=obj.evaluated_get(depsgraph)
            mesh=evaluated.to_mesh()
            try:
                mesh.calc_loop_triangles()
                offset=len(vertices)
                vertices.extend(evaluated.matrix_world @ vertex.co for vertex in mesh.vertices)
                triangles.extend(tuple(offset+index for index in face.vertices) for face in mesh.loop_triangles)
            finally:
                evaluated.to_mesh_clear()
        if not vertices:
            raise ValueError(f"No evaluated vertices for {slot}")
        if not all(math.isfinite(value) for vertex in vertices for value in vertex):
            raise ValueError(f"Nonfinite deformed coordinates in {slot}")
        result[slot]={"vertices":vertices,"triangles":triangles,
                      "minimum_z_m":min(vertex.z for vertex in vertices),
                      "maximum_z_m":max(vertex.z for vertex in vertices)}
    return result


def _overlap_snapshot(assembly):
    geometry=_module_geometry(assembly)
    trees={slot:BVHTree.FromPolygons(value["vertices"],value["triangles"],all_triangles=True,epsilon=0)
           for slot,value in geometry.items() if any(slot in pair for pair in PAIRS)}
    pairs={f"{left}/{right}":len(trees[left].overlap(trees[right])) for left,right in PAIRS}
    return {"overlap_candidates":pairs,"module_ground_bounds_m":{slot:value["minimum_z_m"] for slot,value in geometry.items()},
            "finite_deformed_coordinates":True}


def extreme_pose_audit(assembly):
    review.rest_pose(assembly)
    baseline=_overlap_snapshot(assembly)
    frames=[]
    for name in CLIPS:
        fractions=(0,.25,.417,.625,.75,1) if name=="attack_melee" else (.25,.75)
        for fraction in fractions:
            frame=review.set_clip(assembly,name,fraction)
            snapshot=_overlap_snapshot(assembly)
            increases={pair:count-baseline["overlap_candidates"][pair] for pair,count in snapshot["overlap_candidates"].items()}
            frames.append(dict(snapshot,clip=name,fraction=fraction,frame=frame,joints=_joint_metrics(assembly["rig"]),
                               overlap_candidate_increase=increases))
        print("EXPORTED_MOTION_SAMPLED",name,flush=True)
    return {"method":"Evaluated world-space triangles; cross-module BVH overlap candidate counts compared with rest. Hidden/intended overlaps can trigger candidates.",
            "interpretation":"Neither zero candidates nor positive distances establish collision clearance. Review the targeted pose renders.",
            "rest":baseline,"frames":frames}


def late_death_ground_audit(assembly):
    """Measure the fallen figure independently of the planted-boot solver."""
    records=[]
    for fraction in (.75,.85,.95,1.0):
        frame=review.set_clip(assembly,"death",fraction)
        geometry=_module_geometry(assembly)
        minima={slot:item["minimum_z_m"] for slot,item in geometry.items() if slot!="weapon"}
        lowest_slot=min(minima,key=minima.get)
        records.append({"fraction":fraction,"frame":frame,"module_minimum_z_m":minima,
                        "lowest_body_or_armor_z_m":minima[lowest_slot],"lowest_module":lowest_slot})
    return {"samples":records,"minimum_body_or_armor_z_m":min(item["lowest_body_or_armor_z_m"] for item in records),
            "policy":"Actual evaluated body and every armor module, excluding the weapon; boot support alone does not establish full fallen-body ground fit"}


def render_diagnostic(assembly,clip,fraction,label,closeup=False,focus_bone=None,camera_offset=None,fixed_camera=None):
    frame=review.set_clip(assembly,clip,fraction)
    scene=bpy.context.scene
    scene.render.engine="BLENDER_WORKBENCH"
    scene.display.shading.light="STUDIO"
    scene.display.shading.color_type="SINGLE"
    scene.display.shading.single_color=(.42,.46,.5)
    scene.display.shading.show_shadows=True
    scene.display.shading.show_cavity=True
    scene.display.shading.cavity_type="BOTH"
    scene.display.shading.background_type="WORLD"
    if scene.world is None:
        scene.world=bpy.data.worlds.new("motion_audit_world")
    scene.world.color=(.035,.035,.035)
    data=bpy.data.cameras.new("motion_audit_camera")
    camera=bpy.data.objects.new("motion_audit_camera",data)
    scene.collection.objects.link(camera)
    if fixed_camera:
        target=Vector(fixed_camera["target"])
        camera.location=Vector(fixed_camera["position"])
        data.ortho_scale=fixed_camera["orthographic_scale"]
        geometry=_module_geometry(assembly)
        vertices=[vertex for item in geometry.values() for vertex in item["vertices"]]
    elif closeup:
        target=assembly["rig"].matrix_world @ assembly["rig"].pose.bones[focus_bone].head if focus_bone else (assembly["sockets"]["socket_hand_R"].matrix_world.translation+assembly["sockets"]["socket_hand_L"].matrix_world.translation)*.5
        camera.location=target+Vector(camera_offset or (1.6,-3,1))
        data.ortho_scale=.56 if focus_bone=="hand_L" else .78
    else:
        geometry=_module_geometry(assembly)
        vertices=[vertex for item in geometry.values() for vertex in item["vertices"]]
        target=Vector(tuple((min(v[axis] for v in vertices)+max(v[axis] for v in vertices))*.5 for axis in range(3)))
        camera.location=target+Vector((3,-5,.4))
        data.ortho_scale=2.32
    data.type="ORTHO"
    camera.rotation_euler=(target-camera.location).to_track_quat("-Z","Y").to_euler()
    if not closeup and not fixed_camera:
        inverse=camera.rotation_euler.to_quaternion().inverted()
        projected=[inverse @ (vertex-target) for vertex in vertices]
        width=max(v.x for v in projected)-min(v.x for v in projected)
        height=max(v.y for v in projected)-min(v.y for v in projected)
        data.ortho_scale=max(height,width*864/768)*1.12
    scene.camera=camera
    scene.render.resolution_x,scene.render.resolution_y=fixed_camera["resolution"] if fixed_camera else (768,864)
    scene.render.resolution_percentage=100
    scene.render.image_settings.file_format="PNG"
    output=ROOT/"review"/f"exported_motion_{label}.png"
    scene.render.filepath=str(output)
    framing=None
    if fixed_camera:
        inverse=camera.rotation_euler.to_quaternion().inverted()
        projected=[inverse @ (vertex-target) for vertex in vertices]
        camera_frame=data.view_frame(scene=scene)
        half_width=max(abs(corner.x) for corner in camera_frame)
        half_height=max(abs(corner.y) for corner in camera_frame)
        framing={"maximum_absolute_horizontal_fraction":max(abs(vertex.x)/half_width for vertex in projected),
                 "maximum_absolute_vertical_fraction":max(abs(vertex.y)/half_height for vertex in projected),
                 "policy":"All equipped mesh vertices, including the attached warhammer, must remain within 96% of the fixed frame"}
        if max(framing["maximum_absolute_horizontal_fraction"],framing["maximum_absolute_vertical_fraction"])>.96:
            raise ValueError("Supplemental fixed late-death camera does not contain the entire figure and weapon")
    bpy.ops.render.render(write_still=True)
    bpy.data.objects.remove(camera,do_unlink=True)
    bpy.data.cameras.remove(data)
    return {"path":str(output),"sha256":_digest(output),"clip":clip,"fraction":fraction,"frame":frame,
            "camera_policy":"Supplemental fixed wide camera; original frozen comparison cameras remain unchanged" if fixed_camera else "Explicit diagnostic camera; frozen source comparison cameras are not modified",
            "fixed_camera":fixed_camera,"framing":framing}


def raw_gltf_slerp_support(body_path,feet_path):
    """Evaluate runtime quaternion interpolation and the actual exported boot skin."""
    body=Glb(body_path.read_bytes(),body_path)
    feet=Glb(feet_path.read_bytes(),feet_path)
    nodes=body.document['nodes']; lookup={node.get('name'):i for i,node in enumerate(nodes)}
    parents={child:i for i,node in enumerate(nodes) for child in node.get('children',[])}
    base=[_node_matrix(node).decompose() for node in nodes]
    skin=feet.document['skins'][0]
    names=[feet.document['nodes'][i]['name'] for i in skin['joints']]
    binds=[np.array(_column_matrix(values)) for values in feet.accessor(skin['inverseBindMatrices'])['rows']]
    primitives=[]
    for node in feet.document['nodes']:
     if 'mesh' not in node or 'skin' not in node:continue
     for primitive in feet.document['meshes'][node['mesh']]['primitives']:
      attrs=primitive['attributes']
      positions=np.array(feet.accessor(attrs['POSITION'])['rows'])
      positions=np.c_[positions,np.ones(len(positions))]
      joints=np.array(feet.accessor(attrs['JOINTS_0'])['rows'],dtype=np.int32)
      weights=np.array(feet.accessor(attrs['WEIGHTS_0'])['rows'])
      groups={}
      for joint in range(len(names)):
       vi,wi=np.nonzero(joints==joint)
       if len(vi):groups[joint]=(vi,weights[vi,wi])
      primitives.append((positions,groups))
    def worlds_at(channels,time):
     values=[[value.copy() for value in item] for item in base]
     for node,path,times,outputs,interpolation in channels:
      if nodes[node].get('name')=='root' or path=='scale':continue
      index=min(len(times)-1,max(0,bisect.bisect_right(times,time)-1))
      end=min(index+1,len(times)-1)
      blend=0 if end==index or interpolation=='STEP' else (time-times[index])/(times[end]-times[index])
      blend=min(1,max(0,blend))
      if path=='rotation':
       qa=Quaternion((outputs[index][3],*outputs[index][:3]))
       qb=Quaternion((outputs[end][3],*outputs[end][:3]))
       values[node][1]=qa.slerp(qb,blend)
      elif path=='translation':values[node][0]=Vector(outputs[index]).lerp(Vector(outputs[end]),blend)
      else:raise ValueError('Unsupported target '+path)
     matrices={}
     def world(index):
      if index not in matrices:
       local=Matrix.LocRotScale(*values[index])
       matrices[index]=world(parents[index]) @ local if index in parents else local
      return matrices[index]
     return {name:np.array(world(lookup[name])) for name in names}
    records={}
    for action in body.document['animations']:
     channels=[]
     for channel in action['channels']:
      sampler=action['samplers'][channel['sampler']]
      interpolation=sampler.get('interpolation','LINEAR')
      assert interpolation in {'LINEAR','STEP'},interpolation
      channels.append((channel['target']['node'],channel['target']['path'],[row[0] for row in body.accessor(sampler['input'])['rows']],body.accessor(sampler['output'])['rows'],interpolation))
     first=min(channel[2][0] for channel in channels);last=max(channel[2][-1] for channel in channels)
     name=action['name']; rate=16 if name=='walk' else 8
     count=round((last-first)*24*rate)
     lows=[]
     for sample in range(count+1):
      time=first+(last-first)*sample/count
      worlds=worlds_at(channels,time)
      minimum=float('inf')
      for positions,groups in primitives:
       heights=np.zeros(len(positions))
       for joint,(indices,weights) in groups.items():
        transform=worlds[names[joint]] @ binds[joint]
        heights[indices]+=((positions[indices] @ transform[1])*weights)
       minimum=min(minimum,float(heights.min()))
      lows.append(minimum)
     records[name]={'samples':len(lows),'minimum_support_y_m':min(lows),'maximum_support_y_m':max(lows),'positive_flight_allowed':name in {'run','jump'},'worst_frame':lows.index(min(lows))/rate}
     print('GLTF_SLERP_SUPPORT',name,min(lows),max(lows),flush=True)
    errors=[]
    for name,record in records.items():
     if record['minimum_support_y_m']<-.002:errors.append(name+' penetrates ground below -2 mm')
     if not record['positive_flight_allowed'] and record['maximum_support_y_m']>.002:errors.append(name+' support exceeds 2 mm')
    report={'body_sha256':_digest(body_path),'feet_sha256':_digest(feet_path),'policy':'Raw GLB LINEAR rotations use quaternion SLERP; other transforms use linear interpolation. Root and scale channels are dropped as in Player. Heights are glTF world Y. Actual POSITION, JOINTS_0, WEIGHTS_0 and inverse bind matrices are evaluated.','clips':records,'errors':errors}
    return report


def run(runtime,render=True):
    if not bpy.app.background:
        raise ValueError("Exported-motion audit requires a disposable background Blender process")
    paths={slot:runtime/review.model_name(slot,0) for slot in review.SLOTS}
    missing=[str(path) for path in paths.values() if not path.is_file()]
    if missing:
        raise FileNotFoundError("Awaiting complete LOD0 exports: "+", ".join(missing))
    hashes={slot:_digest(path) for slot,path in paths.items()}
    reference_path=ROOT/"source/rig_reference.dat"
    reference=json.loads(reference_path.read_text())
    assembly=review.assemble(runtime,0)
    fps=bpy.context.scene.render.fps/bpy.context.scene.render.fps_base
    binary=binary_animation_and_rest(paths["body"],reference,fps)
    rest=reimport_rest(assembly,reference)
    grips=grip_audit(assembly)
    extremes=extreme_pose_audit(assembly)
    with game_playback(assembly) as ignored_tracks:
        game_grips=grip_audit(assembly)
        game_support=support_audit(assembly)
        death_ground=late_death_ground_audit(assembly)
    spherical_support=raw_gltf_slerp_support(paths["body"],paths["feet"])
    errors=list(binary["errors"])+spherical_support["errors"]
    if not rest["passed"]:
        errors.append("Reimported rest matrices differ from the frozen source contract")
    for name,record in grips.items():
        if record["maximum_secondary_gap_m"]>.004:
            errors.append(f"{name} exported secondary grip gap exceeds 4 mm: {record['maximum_secondary_gap_m']:.6f} m")
        if record["maximum_primary_gap_m"]>1e-4:
            errors.append(f"{name} primary marker is detached from right socket")
        if record["maximum_wrist_bend_degrees"]>70:
            errors.append(f"{name} has an excessive held-wrist bend after reimport")
    for name,record in game_grips.items():
        if record["maximum_secondary_gap_m"]>.004:
            errors.append(f"{name} game-sanitized grip exceeds 4 mm")
    for name,record in game_support.items():
        if record["minimum_support_z_m"]<-.002:
            errors.append(f"{name} boots penetrate the game ground by more than 2 mm")
        if not record["positive_airborne_clearance_allowed"] and record["maximum_support_z_m"]>.002:
            errors.append(f"{name} planted boot support floats more than 2 mm above the game ground")
    warnings=[]
    if death_ground["minimum_body_or_armor_z_m"]<-.002:
        lowest_death=min(death_ground["samples"],key=lambda item:item["lowest_body_or_armor_z_m"])
        warnings.append({"clip":"death","issue":"Late-death body or armor extends below ground by more than 2 mm",
                         "fraction":lowest_death["fraction"],
                         "minimum_z_m":death_ground["minimum_body_or_armor_z_m"]})
    for entry in extremes["frames"]:
        if min(entry["module_ground_bounds_m"].values())<-.025:
            warnings.append({"clip":entry["clip"],"fraction":entry["fraction"],"issue":"Deformed mesh extends more than 25 mm below the ground plane"})
    evidence=[]
    if render:
        evidence.append(render_diagnostic(assembly,"combat_idle",.25,"guard_contact",closeup=True))
        evidence.append(render_diagnostic(assembly,"attack_melee",grips["attack_melee"]["worst_fraction"],"worst_grip_contact",closeup=True))
        ranked=sorted(extremes["frames"],key=lambda entry:max(entry["overlap_candidate_increase"].values()),reverse=True)
        unique=[]
        for entry in ranked:
            if entry["clip"] not in {item["clip"] for item in unique}:
                unique.append(entry)
        for index,entry in enumerate(unique[:3]):
            evidence.append(render_diagnostic(assembly,entry["clip"],entry["fraction"],f"overlap_candidate_{index+1}"))
        evidence.append(render_diagnostic(assembly,"idle",.25,"book_hand_region",closeup=True,focus_bone="hand_L"))
        evidence.append(render_diagnostic(assembly,"idle",.25,"book_hand_side_region",closeup=True,focus_bone="hand_L",camera_offset=(3,-1,.4)))
        evidence.append(render_diagnostic(assembly,"walk",.25,"walk_book_hand_region",closeup=True,focus_bone="hand_L"))
        evidence.append(render_diagnostic(assembly,"run",.75,"run_book_hand_region",closeup=True,focus_bone="hand_L"))
        evidence.append(render_diagnostic(assembly,"death",.75,"death_shoulder_region",closeup=True,focus_bone="upper_chest"))
        evidence.append(render_diagnostic(assembly,"death",.85,"supplemental_late_death_wide",fixed_camera=SUPPLEMENTAL_LATE_DEATH_CAMERA))
        evidence.append(render_diagnostic(assembly,"attack_melee",.25,"melee_chest_region",closeup=True,focus_bone="upper_chest"))
        if warnings:
            entry=warnings[0]
            evidence.append(render_diagnostic(assembly,entry["clip"],entry["fraction"],"ground_extent"))
    for slot,path in paths.items():
        if _digest(path)!=hashes[slot]:
            errors.append(f"GLB changed during audit: {path.name}")
    report={"schema_version":1,"created_utc":datetime.now(timezone.utc).isoformat(),"blender_version":bpy.app.version_string,
            "status":"failed" if errors else "numerical_checks_passed_pending_visual_review","runtime_directory":str(runtime),
            "animation_correction_version":assembly["rig"].get("animation_correction_version"),
            "model_hashes":hashes,"canonical_reference_sha256":_digest(reference_path),"binary":binary,"reimport_rest":rest,
            "ignored_importer_bone_display_objects":_IGNORED_BONE_DISPLAYS,
            "grips":grips,"extreme_pose_diagnostics":extremes,"warnings":warnings,"errors":errors,"evidence":evidence,
            "raw_gltf_spherical_interpolation":spherical_support,
            "late_death_ground":death_ground,
            "game_playback":{"policy":"Player sanitizer drops all root tracks and every scale track","ignored_curve_count":ignored_tracks,
                             "grips":game_grips,"boot_support":game_support},
            "scope":"Actual exported LOD0 motion, binding, marker contact and overlap diagnostics. No source corrections, no automatic visual/clipping acceptance."}
    output=ROOT/"review/exported_motion_audit.json"
    output.write_text(json.dumps(report,indent=2)+"\n")
    print("EXPORTED_MOTION_AUDIT_COMPLETE",report["status"],str(output),flush=True)
    return report


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runtime",type=Path,default=ROOT/"runtime")
    parser.add_argument("--no-render",action="store_true")
    args=parser.parse_args(sys.argv[sys.argv.index("--")+1:] if "--" in sys.argv else [])
    try:
        run(args.runtime.resolve(),render=not args.no_render)
    except Exception as error:
        output=ROOT/"review/exported_motion_audit.json"
        output.write_text(json.dumps({"status":"failed_to_complete","created_utc":datetime.now(timezone.utc).isoformat(),
            "runtime_directory":str(args.runtime.resolve()),"errors":[str(error)],
            "scope":"Exported-motion audit did not complete; no motion or collision approval"},indent=2)+"\n")
        raise


if __name__=="__main__":
    main()
