"""Serialize literal reference-authored reliquary relief meshes.

The contour, skull patches, dental crowns and each repeat placement are explicit.
No radial geometry, primitives, profiles or scatter are generated by this file.
"""
import json
from pathlib import Path


def make_part(name, vertices, faces, modifiers=(), closed=False, material="brass"):
    vertex_records, uv_lookup = [], {}
    for row in vertices.strip().splitlines():
        values = row.split()
        vertex_records.append({"id": values[0], "co": [float(v) for v in values[1:4]]})
        uv_lookup[values[0]] = [float(v) for v in values[4:6]]
    face_records = []
    for row in faces.strip().splitlines():
        values = row.split()
        region = values[-1][1:] if values[-1].startswith("@") else material
        ids = values[1:-1] if values[-1].startswith("@") else values[1:]
        face_records.append({"id": values[0], "vertices": ids,
                             "uv": [uv_lookup[v] for v in ids], "material": region})
    return {"id": name, "vertices": vertex_records, "faces": face_records,
            "modifiers": list(modifiers), "closed": closed, "landmarks": {},
            "seams": [], "sharp_edges": [], "creases": [], "slot": "chest",
            "rigid_bone": "upper_chest", "transform": {"location": [0, -.216, 1.409],
                "rotation_degrees": [0, 0, 0], "scale": [1, 1, 1]}}


rim = make_part("reliquary_outer_rim", """
O0 0 -.010 .074 .50 .99
O1 .028 -.010 .068 .69 .95
O2 .052 -.010 .052 .85 .84
O3 .069 -.010 .028 .96 .68
O4 .073 -.010 0 .99 .50
O5 .068 -.010 -.028 .95 .31
O6 .051 -.010 -.052 .84 .15
O7 .027 -.010 -.069 .68 .04
O8 0 -.010 -.074 .50 .01
O9 -.027 -.010 -.069 .32 .04
O10 -.051 -.010 -.052 .16 .15
O11 -.068 -.010 -.028 .05 .31
O12 -.073 -.010 0 .01 .50
O13 -.069 -.010 .028 .04 .68
O14 -.052 -.010 .052 .15 .84
O15 -.028 -.010 .068 .31 .95
I0 0 -.012 .060 .50 .90
I1 .023 -.012 .055 .65 .86
I2 .042 -.012 .042 .78 .78
I3 .055 -.012 .023 .86 .65
I4 .059 -.012 0 .90 .50
I5 .055 -.012 -.023 .86 .35
I6 .041 -.012 -.042 .77 .22
I7 .022 -.012 -.056 .65 .13
I8 0 -.012 -.061 .50 .09
I9 -.022 -.012 -.056 .35 .13
I10 -.041 -.012 -.042 .23 .22
I11 -.055 -.012 -.023 .14 .35
I12 -.059 -.012 0 .10 .50
I13 -.055 -.012 .023 .14 .65
I14 -.042 -.012 .042 .22 .78
I15 -.023 -.012 .055 .35 .86
""", """
rim01 O0 I0 I1 O1
rim02 O1 I1 I2 O2
rim03 O2 I2 I3 O3
rim04 O3 I3 I4 O4
rim05 O4 I4 I5 O5
rim06 O5 I5 I6 O6
rim07 O6 I6 I7 O7
rim08 O7 I7 I8 O8
rim09 O8 I8 I9 O9
rim10 O9 I9 I10 O10
rim11 O10 I10 I11 O11
rim12 O11 I11 I12 O12
rim13 O12 I12 I13 O13
rim14 O13 I13 I14 O14
rim15 O14 I14 I15 O15
rim16 O15 I15 I0 O0
""", [{"type": "SOLIDIFY", "thickness": .004, "offset": 0},
         {"type": "BEVEL", "width": .0007, "segments": 2}])
rim["landmarks"] = {"upper_rim": "O0", "left_rim": "O4", "lower_rim": "O8"}

backing = make_part("reliquary_recessed_backing", """
P0 0 .001 .065 .50 .96
P1 .025 .001 .060 .68 .93
P2 .046 .001 .046 .83 .83
P3 .060 .001 .025 .93 .68
P4 .065 .001 0 .96 .50
P5 .060 .001 -.025 .93 .32
P6 .045 .001 -.047 .82 .17
P7 .024 .001 -.061 .67 .07
P8 0 .001 -.066 .50 .03
P9 -.024 .001 -.061 .33 .07
P10 -.045 .001 -.047 .18 .17
P11 -.060 .001 -.025 .07 .32
P12 -.065 .001 0 .03 .50
P13 -.060 .001 .025 .07 .68
P14 -.046 .001 .046 .17 .83
P15 -.025 .001 .060 .32 .93
C 0 -.003 0 .50 .50
""", """
back01 P0 C P1
back02 P1 C P2
back03 P2 C P3
back04 P3 C P4
back05 P4 C P5
back06 P5 C P6
back07 P6 C P7
back08 P7 C P8
back09 P8 C P9
back10 P9 C P10
back11 P10 C P11
back12 P11 C P12
back13 P12 C P13
back14 P13 C P14
back15 P14 C P15
back16 P15 C P0
""", [{"type": "SOLIDIFY", "thickness": .004, "offset": 0},
         {"type": "BEVEL", "width": .0007, "segments": 2}], material="dark_steel")

skull = make_part("reliquary_skull", """
C0 0 -.020 .042 .50 .99
C1 .011 -.018 .041 .63 .98
C2 .019 -.013 .033 .74 .88
C3 .024 -.008 .020 .82 .73
C4 .026 -.006 .002 .88 .51
C5 .021 -.004 -.016 .80 .30
C6 .014 -.003 -.033 .69 .11
C7 0 -.003 -.039 .50 .04
F0 0 -.029 .030 .50 .85
F1 .011 -.028 .030 .64 .85
F2 .020 -.025 .022 .75 .75
F3 .025 -.022 .009 .82 .60
B0 0 -.030 .018 .50 .71
B1 .005 -.033 .018 .57 .71
B2 .013 -.036 .020 .66 .74
B3 .021 -.033 .017 .77 .70
B4 .026 -.030 .007 .83 .58
O0 .004 -.033 .009 .55 .60
O1 .007 -.035 .014 .59 .66
O2 .016 -.035 .015 .70 .68
O3 .022 -.033 .009 .78 .60
O4 .020 -.033 .002 .76 .51
O5 .010 -.035 .000 .63 .49
O6 .005 -.034 .003 .56 .53
I0 .007 -.018 .008 .58 .60
I1 .009 -.017 .011 .61 .64
I2 .015 -.017 .012 .69 .65
I3 .018 -.018 .008 .72 .60
I4 .016 -.018 .003 .70 .54
I5 .011 -.018 .002 .64 .52
I6 .008 -.018 .004 .60 .55
N0 0 -.035 .010 .50 .61
N1 .003 -.036 .001 .54 .50
N2 .006 -.033 -.005 .58 .43
N3 .004 -.033 -.012 .55 .35
N4 0 -.034 -.010 .50 .37
NI0 0 -.018 .003 .50 .54
NI1 .0015 -.019 -.003 .52 .46
NI2 .003 -.019 -.006 .54 .42
NI3 .0015 -.019 -.008 .52 .40
NI4 0 -.019 -.007 .50 .41
Z0 .017 -.037 -.009 .72 .38
Z1 .027 -.030 -.003 .86 .46
Z2 .022 -.028 -.016 .80 .30
Z3 .013 -.033 -.021 .67 .24
M0 0 -.036 -.019 .50 .26
M1 .008 -.036 -.019 .60 .26
M2 .015 -.035 -.019 .70 .26
J0 0 -.025 -.039 .50 .04
J1 .010 -.025 -.038 .64 .05
J2 .019 -.021 -.028 .76 .16
J3 .023 -.017 -.016 .82 .30
G0 0 -.027 -.031 .50 .14
G1 .010 -.027 -.030 .64 .15
G2 .016 -.024 -.024 .72 .22
S0 0 -.006 -.019 .50 .26
S1 .010 -.007 -.019 .63 .26
S2 .016 -.008 -.023 .72 .21
R0 0 .001 .042 .50 .99
R1 .011 .001 .041 .63 .98
R2 .019 .001 .033 .74 .88
R3 .024 .001 .020 .82 .73
R4 .026 .001 .002 .88 .51
R5 .021 .001 -.016 .80 .30
R6 .014 .001 -.033 .69 .11
R7 0 .001 -.039 .50 .04
RC 0 .003 .002 .50 .51
""", """
calvaria01 C0 F0 F1 C1
calvaria02 C1 F1 F2 C2
calvaria03 C2 F2 F3 C3
calvaria04 C3 F3 B4 C4
forehead01 F0 B0 B1 F1
forehead02 F1 B1 B2 F2
forehead03 F2 B2 B3 F3
temporal01 F3 B3 B4
nasal_root01 B0 N0 O0 B1
orbital_brow01 B1 O0 O1 B2
orbital_brow02 B2 O1 O2 B3
orbital_brow03 B3 O2 O3 B4
zygoma01 B4 O3 O4 Z1
zygoma02 B4 Z1 C4
zygoma03 C4 Z1 Z2 C5
orbital01 O0 I0 I1 O1 @dark_steel
orbital02 O1 I1 I2 O2 @dark_steel
orbital03 O2 I2 I3 O3 @dark_steel
orbital04 O3 I3 I4 O4 @dark_steel
orbital05 O4 I4 I5 O5 @dark_steel
orbital06 O5 I5 I6 O6 @dark_steel
orbital07 O6 I6 I0 O0 @dark_steel
orbital_depth I0 I6 I5 I4 I3 I2 I1 @dark_steel
nasal_side01 N0 N1 O6 O0
nasal_side02 N1 N2 Z0 O5 O6
malar01 O5 Z0 Z1 O4
malar02 Z0 Z2 Z1
maxilla01 N2 N3 M1 Z0
maxilla02 N3 N4 M0 M1
maxilla03 Z0 M1 M2 Z3 Z2
nasal_cavity01 N0 NI0 NI1 N1 @dark_steel
nasal_cavity02 N1 NI1 NI2 N2 @dark_steel
nasal_cavity03 N2 NI2 NI3 N3 @dark_steel
nasal_cavity04 N3 NI3 NI4 N4 @dark_steel
nasal_depth NI0 NI4 NI3 NI2 NI1 @dark_steel
maxilla_bottom01 M0 S0 S1 M1
maxilla_bottom02 M1 S1 S2 M2
maxilla_bottom03 M2 S2 Z3
ramus01 Z2 Z3 G2 J3
ramus02 Z2 J3 C5
ramus03 C5 J3 J2 C6
mandible01 J3 G2 G1 J2
mandible02 J2 G1 J1
mandible03 G1 G0 J0 J1
mandible04 J1 J0 C7 C6 J2
oral_floor01 S0 G0 G1 S1 @dark_steel
oral_floor02 S1 G1 G2 S2 @dark_steel
oral_floor03 S2 G2 Z3 @dark_steel
outer01 C1 C0 R0 R1
outer02 C2 C1 R1 R2
outer03 C3 C2 R2 R3
outer04 C4 C3 R3 R4
outer05 C5 C4 R4 R5
outer06 C6 C5 R5 R6
outer07 C7 C6 R6 R7
back01 R1 R0 RC
back02 R2 R1 RC
back03 R3 R2 RC
back04 R4 R3 RC
back05 R5 R4 RC
back06 R6 R5 RC
back07 R7 R6 RC
""", [{"type": "MIRROR", "axis": "X"}, {"type": "SUBSURF", "levels": 1}])
skull["landmarks"] = {"skull_crown": "C0", "jaw_base": "J0", "left_orbit_outer": "O3"}
skull["creases"] = [
    {"edge": ["B1", "B2"], "value": .7},
    {"edge": ["B2", "B3"], "value": .7},
    {"edge": ["B3", "B4"], "value": .5},
    {"edge": ["O0", "O1"], "value": .6},
    {"edge": ["O1", "O2"], "value": .6},
    {"edge": ["O2", "O3"], "value": .6},
    {"edge": ["O3", "O4"], "value": .6},
    {"edge": ["O4", "O5"], "value": .6},
    {"edge": ["O5", "O6"], "value": .6},
    {"edge": ["O6", "O0"], "value": .6},
    {"edge": ["N1", "N2"], "value": .6},
    {"edge": ["N2", "N3"], "value": .6},
    {"edge": ["Z0", "Z1"], "value": .55},
    {"edge": ["Z1", "Z2"], "value": .55},
    {"edge": ["M0", "M1"], "value": .7},
    {"edge": ["M1", "M2"], "value": .7},
    {"edge": ["J0", "J1"], "value": .35},
    {"edge": ["J1", "J2"], "value": .35},
]

tooth = make_part("reliquary_dental_crowns", """
F0 -.0023 -.0010 .0010 .10 .95
F1 .0023 -.0010 .0010 .90 .95
F2 .0028 -.0020 -.0030 .98 .56
F3 .0019 -.0015 -.0090 .80 .05
F4 -.0019 -.0015 -.0090 .20 .05
F5 -.0028 -.0020 -.0030 .02 .56
B0 -.0020 .0030 .0005 .15 .92
B1 .0020 .0030 .0005 .85 .92
B2 .0024 .0030 -.0030 .93 .56
B3 .0015 .0020 -.0080 .75 .12
B4 -.0015 .0020 -.0080 .25 .12
B5 -.0024 .0030 -.0030 .07 .56
""", """
toothface01 F0 F5 F2 F1
toothface02 F5 F4 F3 F2
crown01 F1 B1 B0 F0
crown02 F2 B2 B1 F1
crown03 F3 B3 B2 F2
incisal01 F4 B4 B3 F3
crown04 F5 B5 B4 F4
crown05 F0 B0 B5 F5
root01 B0 B1 B2 B5
root02 B5 B2 B3 B4
""", [{"type": "BEVEL", "width": .00045, "segments": 2}], closed=True)
tooth["instances"] = [
    {"location": [.0030, -.253, 1.388], "rotation_degrees": [0, 0, 0], "scale": [1, 1, 1]},
    {"location": [-.0030, -.253, 1.388], "rotation_degrees": [0, 0, 0], "scale": [1, 1, 1]},
    {"location": [.0087, -.252, 1.388], "rotation_degrees": [0, 0, -8], "scale": [.9, 1, .92]},
    {"location": [-.0087, -.252, 1.388], "rotation_degrees": [0, 0, 8], "scale": [.9, 1, .92]},
    {"location": [.0140, -.249, 1.389], "rotation_degrees": [0, 0, -16], "scale": [.8, .9, 1.10]},
    {"location": [-.0140, -.249, 1.389], "rotation_degrees": [0, 0, 16], "scale": [.8, .9, 1.10]},
]

ray = make_part("reliquary_pointed_rays", """
P0 -.0030 -.008 .046 .33 .08
P1 .0030 -.008 .046 .67 .08
P2 .0045 -.012 .057 .75 .34
P3 .0080 -.010 .062 .96 .49
P4 .0040 -.012 .066 .73 .60
P5 .0025 -.012 .076 .65 .90
P6 0 -.014 .081 .50 .99
P7 -.0025 -.012 .076 .35 .90
P8 -.0040 -.012 .066 .27 .60
P9 -.0080 -.010 .062 .04 .49
P10 -.0045 -.012 .057 .25 .34
R0 0 -.015 .051 .50 .18
R1 0 -.017 .062 .50 .49
R2 0 -.016 .073 .50 .81
""", """
ray01 P0 R0 P1
ray02 P1 R0 R1 P2
ray03 P2 R1 P3
ray04 P3 R1 P4
ray05 P4 R1 R2 P5
ray06 P5 R2 P6
ray07 P6 R2 P7
ray08 P7 R2 R1 P8
ray09 P8 R1 P9
ray10 P9 R1 P10
ray11 P10 R1 R0 P0
""", [{"type": "SOLIDIFY", "thickness": .002, "offset": 0},
         {"type": "BEVEL", "width": .0004, "segments": 2}])
ray["instances"] = [
    {"location": [0, -.216, 1.409], "rotation_degrees": [0, 0, 0], "scale": [1, 1, 1]},
    {"location": [0, -.216, 1.409], "rotation_degrees": [0, 45, 0], "scale": [.85, 1, .92]},
    {"location": [0, -.216, 1.409], "rotation_degrees": [0, 90, 0], "scale": [1, 1, 1]},
    {"location": [0, -.216, 1.409], "rotation_degrees": [0, 135, 0], "scale": [.85, 1, .92]},
    {"location": [0, -.216, 1.409], "rotation_degrees": [0, 180, 0], "scale": [.85, 1, 1.08]},
    {"location": [0, -.216, 1.409], "rotation_degrees": [0, 225, 0], "scale": [.85, 1, .92]},
    {"location": [0, -.216, 1.409], "rotation_degrees": [0, 270, 0], "scale": [1, 1, 1]},
    {"location": [0, -.216, 1.409], "rotation_degrees": [0, 315, 0], "scale": [.85, 1, .92]},
]

inner_collar = make_part("reliquary_inner_beaded_border", """
O0 0 -.014 .052 .50 .96
O1 .020 -.014 .048 .68 .92
O2 .037 -.014 .037 .83 .83
O3 .048 -.014 .020 .92 .68
O4 .052 -.014 0 .96 .50
O5 .048 -.014 -.020 .92 .32
O6 .037 -.014 -.037 .83 .17
O7 .020 -.014 -.048 .68 .08
O8 0 -.014 -.052 .50 .04
O9 -.020 -.014 -.048 .32 .08
O10 -.037 -.014 -.037 .17 .17
O11 -.048 -.014 -.020 .08 .32
O12 -.052 -.014 0 .04 .50
O13 -.048 -.014 .020 .08 .68
O14 -.037 -.014 .037 .17 .83
O15 -.020 -.014 .048 .32 .92
I0 0 -.015 .048 .50 .92
I1 .018 -.015 .044 .66 .88
I2 .034 -.015 .034 .80 .80
I3 .044 -.015 .018 .88 .66
I4 .048 -.015 0 .92 .50
I5 .044 -.015 -.018 .88 .34
I6 .034 -.015 -.034 .80 .20
I7 .018 -.015 -.044 .66 .12
I8 0 -.015 -.048 .50 .08
I9 -.018 -.015 -.044 .34 .12
I10 -.034 -.015 -.034 .20 .20
I11 -.044 -.015 -.018 .12 .34
I12 -.048 -.015 0 .08 .50
I13 -.044 -.015 .018 .12 .66
I14 -.034 -.015 .034 .20 .80
I15 -.018 -.015 .044 .34 .88
""", """
border01 O0 I0 I1 O1
border02 O1 I1 I2 O2
border03 O2 I2 I3 O3
border04 O3 I3 I4 O4
border05 O4 I4 I5 O5
border06 O5 I5 I6 O6
border07 O6 I6 I7 O7
border08 O7 I7 I8 O8
border09 O8 I8 I9 O9
border10 O9 I9 I10 O10
border11 O10 I10 I11 O11
border12 O11 I11 I12 O12
border13 O12 I12 I13 O13
border14 O13 I13 I14 O14
border15 O14 I14 I15 O15
border16 O15 I15 I0 O0
""", [{"type": "SOLIDIFY", "thickness": .002, "offset": 0},
         {"type": "BEVEL", "width": .0006, "segments": 2}])

pendant = make_part("reliquary_lower_pendant", """
P0 -.004 -.015 -.073 .35 .98
P1 .004 -.015 -.073 .65 .98
P2 .004 -.015 -.084 .65 .78
P3 .011 -.015 -.084 .94 .78
P4 .012 -.015 -.089 .98 .68
P5 .005 -.015 -.089 .70 .68
P6 .005 -.015 -.100 .70 .45
P7 .009 -.015 -.103 .86 .38
P8 0 -.015 -.118 .50 .05
P9 -.009 -.015 -.103 .14 .38
P10 -.005 -.015 -.100 .30 .45
P11 -.005 -.015 -.089 .30 .68
P12 -.012 -.015 -.089 .02 .68
P13 -.011 -.015 -.084 .06 .78
P14 -.004 -.015 -.084 .35 .78
C0 0 -.020 -.086 .50 .74
C1 0 -.021 -.103 .50 .38
""", """
pendant01 P0 P14 C0 P1
pendant02 P1 C0 P2
pendant03 P2 C0 P3
pendant04 P3 C0 P4
pendant05 P4 C0 P5
pendant06 P5 C0 C1 P6
pendant07 P6 C1 P7
pendant08 P7 C1 P8
pendant09 P8 C1 P9
pendant10 P9 C1 P10
pendant11 P10 C1 C0 P11
pendant12 P11 C0 P12
pendant13 P12 C0 P13
pendant14 P13 C0 P14
""", [{"type": "SOLIDIFY", "thickness": .003, "offset": 0},
         {"type": "BEVEL", "width": .00065, "segments": 2}])

stud = make_part("reliquary_rim_fasteners", """
P0 0 0 .0030 .50 .99
P1 .0021 0 .0021 .85 .85
P2 .0030 0 0 .99 .50
P3 .0021 0 -.0021 .85 .15
P4 0 0 -.0030 .50 .01
P5 -.0021 0 -.0021 .15 .15
P6 -.0030 0 0 .01 .50
P7 -.0021 0 .0021 .15 .85
F 0 -.0022 0 .50 .50
B 0 .0012 0 .50 .50
""", """
stud01 P0 F P1
stud02 P1 F P2
stud03 P2 F P3
stud04 P3 F P4
stud05 P4 F P5
stud06 P5 F P6
stud07 P6 F P7
stud08 P7 F P0
stud09 P1 B P0
stud10 P2 B P1
stud11 P3 B P2
stud12 P4 B P3
stud13 P5 B P4
stud14 P6 B P5
stud15 P7 B P6
stud16 P0 B P7
""", [{"type": "SUBSURF", "levels": 1}], closed=True)
stud["instances"] = [
    {"location": [0, -.231, 1.476], "rotation_degrees": [0, 0, 0], "scale": [1, 1, 1]},
    {"location": [.047, -.231, 1.456], "rotation_degrees": [0, 0, 0], "scale": [1, 1, 1]},
    {"location": [.066, -.231, 1.409], "rotation_degrees": [0, 0, 0], "scale": [1, 1, 1]},
    {"location": [.047, -.231, 1.362], "rotation_degrees": [0, 0, 0], "scale": [1, 1, 1]},
    {"location": [0, -.231, 1.342], "rotation_degrees": [0, 0, 0], "scale": [1, 1, 1]},
    {"location": [-.047, -.231, 1.362], "rotation_degrees": [0, 0, 0], "scale": [1, 1, 1]},
    {"location": [-.066, -.231, 1.409], "rotation_degrees": [0, 0, 0], "scale": [1, 1, 1]},
    {"location": [-.047, -.231, 1.456], "rotation_degrees": [0, 0, 0], "scale": [1, 1, 1]},
]

document = {
    "schema_version": 1,
    "component": "medallion",
    "reference_notes": [
        "The medallion inset and large front breastplate guide the relief: exposed skull, recessed orbits, separate dental crowns, nested brass rings and pointed lower pendant.",
        "The skull is a fresh literal mesh, not a head copy or primitive. Orbital and nasal cavities have explicit inset surfaces; the rear relief is closed at a conservative attachment depth.",
        "Eight individually listed instances place the authored pointed rays. Six individually listed dental crowns retain authored shapes and transforms; no scattering or automatic radial placement is used.",
        "The attachment center is (0,-.216,1.409) m. Wheel diameter is approximately .148 m; rays and the hanging pointed pendant extend beyond it.",
        "Preview brass and dark steel assignments are not finished baked material maps. Final wear and engraving are subsequent surface work."
    ],
    "parts": [backing, rim, inner_collar, skull, tooth, ray, pendant, stud],
}

if __name__ == "__main__":
    output = Path(__file__).resolve().parents[1] / "source" / "medallion.json"
    output.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    print(output)
    print({"parts": len(document["parts"]),
           "control_vertices": sum(len(p["vertices"]) for p in document["parts"]),
           "control_faces": sum(len(p["faces"]) for p in document["parts"])})
