/** Local-only MCP facade for the reviewed character asset pipeline. */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { cancelModelJob, getModelJob } from "../tools/model-jobs.mjs";
import { recordModelReview, startWorkflowJob } from "../tools/model-workflow.mjs";
import { structuredError } from "../tools/workspace-paths.mjs";

const JOB_RESPONSE = {
  type: "object",
  properties: {
    jobId: { type: "string" },
    status: { type: "string" },
    progress: { type: "number" },
  },
};

const PROVENANCE_PROPERTIES = {
  provider: {
    type: "object",
    properties: {
      name: { type: "string", description: "Local/open-source tool or original authoring workflow." },
      taskId: { type: "string" },
      modelVersion: { type: "string" },
      seed: { type: ["integer", "string"] },
    },
    required: ["name", "modelVersion"],
  },
  license: {
    type: "object",
    properties: {
      name: { type: "string" },
      sourceUrl: { type: "string" },
      termsUrl: { type: "string" },
    },
    required: ["name", "sourceUrl"],
  },
  author: { type: "string" },
  promptSha256: { type: "string" },
  referenceSha256: { type: "array", items: { type: "string" } },
};

const tools = [
  {
    name: "create_body_family",
    description: "Prepare a pinned MPFB 2.0.16 body recipe, or ingest a body GLB generated locally from that recipe. No network or paid API is used.",
    inputSchema: {
      type: "object",
      properties: {
        bodyFamily: { type: "string", enum: ["civic_humanoid_v2", "mire_brutish_v1"] },
        bodyVariant: { type: "string", enum: ["m", "f"] },
        sourceModel: { type: "string", description: "Optional workspace-relative GLB generated by local MPFB." },
        qcPath: { type: "string" },
        assetId: { type: "string" },
        outputModel: { type: "string" },
        runtime: { type: "object" },
        ...PROVENANCE_PROPERTIES,
      },
      required: ["bodyFamily", "bodyVariant"],
    },
    outputSchema: JOB_RESPONSE,
  },
  {
    name: "ingest_generated_candidate",
    description: "Copy a local GLB candidate into an immutable job workspace and record hashes, license, provider, family, skeleton, and draft lifecycle.",
    inputSchema: {
      type: "object",
      properties: {
        sourcePath: { type: "string" },
        qcPath: { type: "string" },
        assetId: { type: "string" },
        displayName: { type: "string" },
        category: { type: "string", enum: ["character", "body", "armor", "weapon", "jewel", "prop", "terrain"] },
        outputModel: { type: "string" },
        bodyFamily: { type: "string" },
        bodyVariant: { type: "string", enum: ["m", "f"] },
        skeletonId: { type: "string", default: "humanoid_game_v2" },
        bindPoseId: { type: "string", default: "a_pose_v2" },
        runtime: { type: "object" },
        ...PROVENANCE_PROPERTIES,
      },
      required: ["sourcePath", "assetId", "bodyFamily", "bodyVariant", "provider", "license"],
    },
    outputSchema: JOB_RESPONSE,
  },
  {
    name: "build_modular_set",
    description: "Validate and stage exactly nine independently segmented local armor modules. Fused candidates are rejected instead of silently promoted.",
    inputSchema: {
      type: "object",
      properties: {
        setId: { type: "string" },
        bodyFamily: { type: "string" },
        bodyVariant: { type: "string", enum: ["m", "f"] },
        skeletonId: { type: "string", default: "humanoid_game_v2" },
        bindPoseId: { type: "string", default: "a_pose_v2" },
        bodyModel: { type: "string" },
        provenance: {
          type: "object",
          properties: {
            provider: PROVENANCE_PROPERTIES.provider,
            license: PROVENANCE_PROPERTIES.license,
            author: PROVENANCE_PROPERTIES.author,
            promptSha256: PROVENANCE_PROPERTIES.promptSha256,
            referenceSha256: PROVENANCE_PROPERTIES.referenceSha256,
          },
          required: ["provider", "license"],
        },
        modules: {
          type: "object",
          description: "Keys: head, shoulders, chest, hands, waist, legs, feet, back, tabard.",
          additionalProperties: {
            type: "object",
            properties: {
              modelPath: { type: "string" },
              qcPath: { type: "string" },
              assetId: { type: "string" },
              outputModel: { type: "string" },
              itemKey: { type: "string" },
              displayName: { type: "string" },
              skinned: { type: "boolean" },
              coveredRegions: { type: "array", items: { type: "string" } },
            },
            required: ["modelPath", "qcPath"],
          },
        },
      },
      required: ["setId", "bodyFamily", "bodyVariant", "bodyModel", "modules", "provenance"],
    },
    outputSchema: JOB_RESPONSE,
  },
  {
    name: "validate_model_asset",
    description: "Run strict manifest/index/QC validation for a blueprint, or validate a workspace GLB against its hash-bound QC sidecar.",
    inputSchema: {
      type: "object",
      properties: {
        ref: { type: "string" },
        modelPath: { type: "string" },
        qcPath: { type: "string" },
        assetId: { type: "string" },
        strict: { type: "boolean", default: true },
      },
    },
    outputSchema: JOB_RESPONSE,
  },
  {
    name: "render_model_review",
    description: "Render four orthographic review views and optional hash-bound animation evidence in local Blender. The focused profile samples side/back locomotion and front/side melee key phases. No cloud renderer is called.",
    inputSchema: {
      type: "object",
      properties: {
        modelPath: { type: "string" },
        ref: { type: "string" },
        sourceJobId: { type: "string" },
        assetId: { type: "string" },
        reviewType: { type: "string", enum: ["bare_body", "fully_equipped"] },
        includeAnimations: { type: "boolean", default: false },
        animationEvidenceProfile: {
          type: "string",
          enum: ["midpoint", "locomotion_melee_key_phases"],
          default: "midpoint",
        },
        requiredClips: { type: "array", items: { type: "string" } },
        resolution: { type: "integer", minimum: 256, maximum: 2048, default: 768 },
        timeoutMs: { type: "integer", minimum: 1000 },
      },
      required: ["reviewType"],
    },
    outputSchema: JOB_RESPONSE,
  },
  {
    name: "get_model_job",
    description: "Read durable status, progress, structured errors, results, and artifact paths for a model job.",
    inputSchema: { type: "object", properties: { jobId: { type: "string" } }, required: ["jobId"] },
  },
  {
    name: "cancel_model_job",
    description: "Request cancellation of a queued or running local model job and terminate its Blender subprocess when possible.",
    inputSchema: { type: "object", properties: { jobId: { type: "string" } }, required: ["jobId"] },
  },
  {
    name: "record_model_review",
    description: "Record an explicit human approval or rejection. Approval requires bare/equipped four-view renders, all animation clips, and affirmative anatomy/material/seam/clipping checks.",
    inputSchema: {
      type: "object",
      properties: {
        targetJobId: { type: "string" },
        decision: { type: "string", enum: ["approved", "rejected"] },
        reviewer: { type: "string" },
        bareBodyRenderJobId: { type: "string" },
        equippedRenderJobId: { type: "string" },
        checks: {
          type: "object",
          properties: {
            anatomyNatural: { type: "boolean" },
            materialsPbr: { type: "boolean" },
            seamsAcceptable: { type: "boolean" },
            clippingAcceptable: { type: "boolean" },
            animationsAcceptable: { type: "boolean" },
          },
        },
        notes: { type: "string" },
      },
      required: ["targetJobId", "decision", "reviewer"],
    },
  },
  {
    name: "promote_model_set",
    description: "Hash-check and atomically publish an explicitly approved bundle, then rebuild the deterministic approved-only runtime registry.",
    inputSchema: { type: "object", properties: { targetJobId: { type: "string" } }, required: ["targetJobId"] },
    outputSchema: JOB_RESPONSE,
  },
];

function result(value, isError = false) {
  return {
    content: [{ type: "text", text: JSON.stringify(value, null, 2) }],
    ...(isError ? { isError: true } : {}),
  };
}

const server = new Server(
  { name: "war-js-local-character-pipeline", version: "3.0.0" },
  { capabilities: { tools: {} } },
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools }));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args = {} } = request.params;
  try {
    if (["create_body_family", "ingest_generated_candidate", "build_modular_set", "validate_model_asset", "render_model_review", "promote_model_set"].includes(name)) {
      return result(startWorkflowJob(name, args));
    }
    if (name === "get_model_job") return result(getModelJob(args.jobId));
    if (name === "cancel_model_job") return result(cancelModelJob(args.jobId));
    if (name === "record_model_review") return result(recordModelReview(args));
    return result({ error: { code: "UNKNOWN_TOOL", message: `Unknown tool: ${name}`, retryable: false } }, true);
  } catch (error) {
    return result({ error: structuredError(error) }, true);
  }
});

const transport = new StdioServerTransport();
await server.connect(transport);
process.stderr.write("[character-pipeline-mcp] local-only reviewed asset server ready\n");
