"""Freeze original source, retained utility references and build/review tools."""
from pathlib import Path
import hashlib,json
ROOT=Path(__file__).resolve().parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
record={'schemaVersion':1,'source':'source/nature.json','sourceSha256':sha(ROOT/'source/nature.json'),'geometry':'Original botanical paths, irregular section coordinates, thick blade outlines and cooling-fracture surveys expanded to inspectable mesh/UV records. No imported models or primitive constructors.','textures':'Eight new painted PBR fields. Retained utility sources contain no reused geometry or pixels.','tools':{str(p.relative_to(ROOT)).replace('\\','/'):sha(p) for p in sorted((ROOT/'tools').glob('*')) if p.suffix in ('.py','.mjs')},'retainedUtilityReferences':{str(p.relative_to(ROOT)).replace('\\','/'):sha(p) for p in sorted((ROOT/'source/references').glob('*'))},'referenceReading':[{'title':'RHS: Alnus glutinosa','url':'https://www.rhs.org.uk/plants/897/alnus-glutinosa/details','use':'Rounded alder leaves and damp-ground habit; Cinderfen steam damage and autumn pigment are original art direction.'},{'title':'RHS: Phragmites australis','url':'https://www.rhs.org.uk/plants/54026/phragmites-australis/details','use':'Erect culms, drooping linear leaves, terminal branched panicles and autumn browning.'},{'title':'RHS: Equisetum palustre','url':'https://www.rhs.org.uk/plants/131504/equisetum-palustre/details','use':'Small jointed stems with upward slender branches in whorls.'},{'title':'USGS: columnar jointing and cooling history','url':'https://www.usgs.gov/observatories/hvo/news/volcano-watch-columnar-jointing-provides-clues-cooling-history-lava-flows','use':'Irregular rapid-cooling fractures; no regular column assembly or image copying.'}]}
record['retainedExporterSources']={str(p.relative_to(ROOT)).replace('\\','/'):sha(p) for p in sorted((ROOT/'review/tool_sources').glob('*.py'))}
(ROOT/'source/provenance.json').write_text(json.dumps(record,indent=2)+'\n')
print('Frozen original source and',len(record['tools']),'tools')
