// Generated by scripts/campaign/generate-static-campaign.mjs. Do not edit by hand.
export const CAMPAIGN_STATIC_VERSION = "aegis-riftbound-v1" as const;

export const CAMPAIGN_REALMS = {
  "aegis": {
    "id": "aegis",
    "label": "Aegis Accord",
    "shortLabel": "Aegis",
    "capitalZoneId": "aegis_capital",
    "enemyCapitalZoneId": "riftspire_capital"
  },
  "riftbound": {
    "id": "riftbound",
    "label": "Riftbound Host",
    "shortLabel": "Riftbound",
    "capitalZoneId": "riftspire_capital",
    "enemyCapitalZoneId": "aegis_capital"
  }
} as const;

export const CAMPAIGN_LANE_LABELS = {
  "central": "Central Front",
  "aegis_west": "Aegis West March",
  "aegis_east": "Aegis East March",
  "riftbound_west": "Riftbound West March",
  "riftbound_east": "Riftbound East March"
} as const;

export const CAMPAIGN_NODES = [
  {
    "id": "aegis_capital",
    "name": "Bastion of Aegis",
    "realm": "aegis",
    "tier": "City",
    "lane": "central",
    "nodeRole": "capital",
    "theme": "aegis_city",
    "levelBand": "Capital",
    "staticMapHash": "377d653c3b4ae130"
  },
  {
    "id": "aegis_gate_fortress",
    "name": "Starfall Gate",
    "realm": "aegis",
    "tier": "Fortress",
    "lane": "central",
    "nodeRole": "fortress",
    "theme": "aegis_fortress",
    "levelBand": "Endgame",
    "staticMapHash": "f172c92d101d3225"
  },
  {
    "id": "aegis_crownworks",
    "name": "Aegis Crownworks",
    "realm": "aegis",
    "tier": "T4",
    "lane": "central",
    "nodeRole": "battlefield",
    "theme": "aegis_highlands",
    "levelBand": "Tier 4",
    "staticMapHash": "b59275b498b06b0f"
  },
  {
    "id": "dawnline_expanse",
    "name": "Dawnline Expanse",
    "realm": "aegis",
    "tier": "T4",
    "lane": "central",
    "nodeRole": "battlefield",
    "theme": "frontier_grassland",
    "levelBand": "Tier 4",
    "staticMapHash": "216fb79fac1d3599"
  },
  {
    "id": "shatterline_expanse",
    "name": "Shatterline Expanse",
    "realm": "riftbound",
    "tier": "T4",
    "lane": "central",
    "nodeRole": "battlefield",
    "theme": "rift_frontier",
    "levelBand": "Tier 4",
    "staticMapHash": "676428efbba4a390"
  },
  {
    "id": "rift_crownworks",
    "name": "Rift Crownworks",
    "realm": "riftbound",
    "tier": "T4",
    "lane": "central",
    "nodeRole": "battlefield",
    "theme": "rift_highlands",
    "levelBand": "Tier 4",
    "staticMapHash": "46736cea1e78fe02"
  },
  {
    "id": "rift_gate_fortress",
    "name": "Voidgate Fortress",
    "realm": "riftbound",
    "tier": "Fortress",
    "lane": "central",
    "nodeRole": "fortress",
    "theme": "rift_fortress",
    "levelBand": "Endgame",
    "staticMapHash": "bcb5ea1934a1fba5"
  },
  {
    "id": "riftspire_capital",
    "name": "Riftspire Citadel",
    "realm": "riftbound",
    "tier": "City",
    "lane": "central",
    "nodeRole": "capital",
    "theme": "rift_city",
    "levelBand": "Capital",
    "staticMapHash": "7534a54b6d02d4b3"
  },
  {
    "id": "sunmeadow_march",
    "name": "Sunmeadow March",
    "realm": "aegis",
    "tier": "T1",
    "lane": "aegis_west",
    "nodeRole": "battlefield",
    "theme": "sunlit_fields",
    "levelBand": "Tier 1",
    "staticMapHash": "31d3e4fff98eb6be"
  },
  {
    "id": "greybrook_crossing",
    "name": "Greybrook Crossing",
    "realm": "aegis",
    "tier": "T2",
    "lane": "aegis_west",
    "nodeRole": "battlefield",
    "theme": "river_crossing",
    "levelBand": "Tier 2",
    "staticMapHash": "3c66e8dd6ef4547d"
  },
  {
    "id": "ironwood_redoubt",
    "name": "Ironwood Redoubt",
    "realm": "aegis",
    "tier": "T3",
    "lane": "aegis_west",
    "nodeRole": "battlefield",
    "theme": "ironwood_forest",
    "levelBand": "Tier 3",
    "staticMapHash": "9425337076c8051b"
  },
  {
    "id": "brightfen_approach",
    "name": "Brightfen Approach",
    "realm": "aegis",
    "tier": "T1",
    "lane": "aegis_east",
    "nodeRole": "battlefield",
    "theme": "brightfen",
    "levelBand": "Tier 1",
    "staticMapHash": "7b9908d54fe63dcc"
  },
  {
    "id": "glassriver_ford",
    "name": "Glassriver Ford",
    "realm": "aegis",
    "tier": "T2",
    "lane": "aegis_east",
    "nodeRole": "battlefield",
    "theme": "glassriver",
    "levelBand": "Tier 2",
    "staticMapHash": "720aa8456a275448"
  },
  {
    "id": "highvale_rampart",
    "name": "Highvale Rampart",
    "realm": "aegis",
    "tier": "T3",
    "lane": "aegis_east",
    "nodeRole": "battlefield",
    "theme": "highvale",
    "levelBand": "Tier 3",
    "staticMapHash": "556a438c1bd1c30d"
  },
  {
    "id": "cinderfen_outskirts",
    "name": "Cinderfen Outskirts",
    "realm": "riftbound",
    "tier": "T1",
    "lane": "riftbound_west",
    "nodeRole": "battlefield",
    "theme": "cinderfen",
    "levelBand": "Tier 1",
    "staticMapHash": "14fb64f2045f527b"
  },
  {
    "id": "bleakroot_causeway",
    "name": "Bleakroot Causeway",
    "realm": "riftbound",
    "tier": "T2",
    "lane": "riftbound_west",
    "nodeRole": "battlefield",
    "theme": "bleakroot",
    "levelBand": "Tier 2",
    "staticMapHash": "0af88d0094148108"
  },
  {
    "id": "vilemere_heights",
    "name": "Vilemere Heights",
    "realm": "riftbound",
    "tier": "T3",
    "lane": "riftbound_west",
    "nodeRole": "battlefield",
    "theme": "vilemere",
    "levelBand": "Tier 3",
    "staticMapHash": "d178694b45279d2b"
  },
  {
    "id": "ashen_steppe",
    "name": "Ashen Steppe",
    "realm": "riftbound",
    "tier": "T1",
    "lane": "riftbound_east",
    "nodeRole": "battlefield",
    "theme": "ashen_steppe",
    "levelBand": "Tier 1",
    "staticMapHash": "b4eaa8053c507a02"
  },
  {
    "id": "gorepine_pass",
    "name": "Gorepine Pass",
    "realm": "riftbound",
    "tier": "T2",
    "lane": "riftbound_east",
    "nodeRole": "battlefield",
    "theme": "gorepine",
    "levelBand": "Tier 2",
    "staticMapHash": "0038e7a9378b52f5"
  },
  {
    "id": "obsidian_scar",
    "name": "Obsidian Scar",
    "realm": "riftbound",
    "tier": "T3",
    "lane": "riftbound_east",
    "nodeRole": "battlefield",
    "theme": "obsidian_scar",
    "levelBand": "Tier 3",
    "staticMapHash": "9b4236846440d189"
  },
  {
    "id": "wardens_hollow",
    "name": "Warden's Hollow",
    "realm": "aegis",
    "tier": "Boss",
    "lane": "aegis_west",
    "nodeRole": "boss_lair",
    "theme": "sunlit_lair",
    "levelBand": "Tier 1 Boss",
    "staticMapHash": "4585f5a6200091f4"
  },
  {
    "id": "briarwatch_den",
    "name": "Briarwatch Den",
    "realm": "aegis",
    "tier": "Boss",
    "lane": "aegis_west",
    "nodeRole": "boss_lair",
    "theme": "briar_lair",
    "levelBand": "Tier 2 Boss",
    "staticMapHash": "70cba516beaffdf7"
  },
  {
    "id": "stormbarrow_lair",
    "name": "Stormbarrow Lair",
    "realm": "aegis",
    "tier": "Boss",
    "lane": "aegis_west",
    "nodeRole": "boss_lair",
    "theme": "storm_lair",
    "levelBand": "Tier 3 Boss",
    "staticMapHash": "151cc53296644823"
  },
  {
    "id": "mireglass_den",
    "name": "Mireglass Den",
    "realm": "aegis",
    "tier": "Boss",
    "lane": "aegis_east",
    "nodeRole": "boss_lair",
    "theme": "mire_lair",
    "levelBand": "Tier 1 Boss",
    "staticMapHash": "eecba7b9165cbe77"
  },
  {
    "id": "glassriver_depths",
    "name": "Glassriver Depths",
    "realm": "aegis",
    "tier": "Boss",
    "lane": "aegis_east",
    "nodeRole": "boss_lair",
    "theme": "river_lair",
    "levelBand": "Tier 2 Boss",
    "staticMapHash": "b23a82527e4d7dbb"
  },
  {
    "id": "highvale_sanctum",
    "name": "Highvale Sanctum",
    "realm": "aegis",
    "tier": "Boss",
    "lane": "aegis_east",
    "nodeRole": "boss_lair",
    "theme": "sanctum_lair",
    "levelBand": "Tier 3 Boss",
    "staticMapHash": "5847a5296c50b785"
  },
  {
    "id": "cindermaw_pit",
    "name": "Cindermaw Pit",
    "realm": "riftbound",
    "tier": "Boss",
    "lane": "riftbound_west",
    "nodeRole": "boss_lair",
    "theme": "cinder_lair",
    "levelBand": "Tier 1 Boss",
    "staticMapHash": "82a0e5b5d58647c8"
  },
  {
    "id": "rotwreath_nest",
    "name": "Rotwreath Nest",
    "realm": "riftbound",
    "tier": "Boss",
    "lane": "riftbound_west",
    "nodeRole": "boss_lair",
    "theme": "rot_lair",
    "levelBand": "Tier 2 Boss",
    "staticMapHash": "9ce17ec3615d5ff2"
  },
  {
    "id": "nightglass_hollow",
    "name": "Nightglass Hollow",
    "realm": "riftbound",
    "tier": "Boss",
    "lane": "riftbound_west",
    "nodeRole": "boss_lair",
    "theme": "night_lair",
    "levelBand": "Tier 3 Boss",
    "staticMapHash": "b06bca1e8e6d8da8"
  },
  {
    "id": "ashfang_pit",
    "name": "Ashfang Pit",
    "realm": "riftbound",
    "tier": "Boss",
    "lane": "riftbound_east",
    "nodeRole": "boss_lair",
    "theme": "ash_lair",
    "levelBand": "Tier 1 Boss",
    "staticMapHash": "b1f4c36b6135bb92"
  },
  {
    "id": "gorepine_warrens",
    "name": "Gorepine Warrens",
    "realm": "riftbound",
    "tier": "Boss",
    "lane": "riftbound_east",
    "nodeRole": "boss_lair",
    "theme": "gorepine_lair",
    "levelBand": "Tier 2 Boss",
    "staticMapHash": "debd377673540433"
  },
  {
    "id": "obsidian_maw",
    "name": "Obsidian Maw",
    "realm": "riftbound",
    "tier": "Boss",
    "lane": "riftbound_east",
    "nodeRole": "boss_lair",
    "theme": "obsidian_lair",
    "levelBand": "Tier 3 Boss",
    "staticMapHash": "07c3a7f0567d9ef1"
  }
] as const;

export const CAMPAIGN_EDGES = [
  [
    "riftspire_capital",
    "rift_gate_fortress"
  ],
  [
    "rift_gate_fortress",
    "rift_crownworks"
  ],
  [
    "rift_crownworks",
    "shatterline_expanse"
  ],
  [
    "shatterline_expanse",
    "dawnline_expanse"
  ],
  [
    "dawnline_expanse",
    "aegis_crownworks"
  ],
  [
    "aegis_crownworks",
    "aegis_gate_fortress"
  ],
  [
    "aegis_gate_fortress",
    "aegis_capital"
  ],
  [
    "aegis_capital",
    "sunmeadow_march"
  ],
  [
    "sunmeadow_march",
    "greybrook_crossing"
  ],
  [
    "greybrook_crossing",
    "ironwood_redoubt"
  ],
  [
    "ironwood_redoubt",
    "aegis_crownworks"
  ],
  [
    "sunmeadow_march",
    "wardens_hollow"
  ],
  [
    "greybrook_crossing",
    "briarwatch_den"
  ],
  [
    "ironwood_redoubt",
    "stormbarrow_lair"
  ],
  [
    "aegis_capital",
    "brightfen_approach"
  ],
  [
    "brightfen_approach",
    "glassriver_ford"
  ],
  [
    "glassriver_ford",
    "highvale_rampart"
  ],
  [
    "highvale_rampart",
    "aegis_crownworks"
  ],
  [
    "brightfen_approach",
    "mireglass_den"
  ],
  [
    "glassriver_ford",
    "glassriver_depths"
  ],
  [
    "highvale_rampart",
    "highvale_sanctum"
  ],
  [
    "riftspire_capital",
    "cinderfen_outskirts"
  ],
  [
    "cinderfen_outskirts",
    "bleakroot_causeway"
  ],
  [
    "bleakroot_causeway",
    "vilemere_heights"
  ],
  [
    "vilemere_heights",
    "rift_crownworks"
  ],
  [
    "cinderfen_outskirts",
    "cindermaw_pit"
  ],
  [
    "bleakroot_causeway",
    "rotwreath_nest"
  ],
  [
    "vilemere_heights",
    "nightglass_hollow"
  ],
  [
    "riftspire_capital",
    "ashen_steppe"
  ],
  [
    "ashen_steppe",
    "gorepine_pass"
  ],
  [
    "gorepine_pass",
    "obsidian_scar"
  ],
  [
    "obsidian_scar",
    "rift_crownworks"
  ],
  [
    "ashen_steppe",
    "ashfang_pit"
  ],
  [
    "gorepine_pass",
    "gorepine_warrens"
  ],
  [
    "obsidian_scar",
    "obsidian_maw"
  ]
] as const;

export const CAMPAIGN_OBJECTIVES = {
  "aegis_capital": [
    {
      "id": "aegis_capital_courtyard",
      "type": "battle_objective",
      "label": "1 · Crownwatch Courtyard",
      "x": 0,
      "z": 158,
      "captureRadius": 12,
      "defaultRealm": "aegis"
    },
    {
      "id": "aegis_capital_vault",
      "type": "battle_objective",
      "label": "2 · Crownwatch Vault",
      "x": 114,
      "z": 332,
      "captureRadius": 10,
      "defaultRealm": "aegis",
      "requiresObjectiveIds": [
        "aegis_capital_courtyard"
      ]
    },
    {
      "id": "aegis_capital_throne_room",
      "type": "battle_objective",
      "label": "3 · Crownwatch Throne Room",
      "x": 0,
      "z": 350,
      "captureRadius": 10,
      "defaultRealm": "aegis",
      "requiresObjectiveIds": [
        "aegis_capital_courtyard",
        "aegis_capital_vault"
      ]
    }
  ],
  "aegis_gate_fortress": [
    {
      "id": "aegis_gate_fortress_west_objective",
      "type": "battle_objective",
      "label": "West Siege Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "aegis_gate_fortress_central_objective",
      "type": "battle_objective",
      "label": "Central Siege Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "aegis_gate_fortress_east_objective",
      "type": "battle_objective",
      "label": "East Siege Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "aegis_gate_fortress_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "aegis_gate_fortress_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "aegis_crownworks": [
    {
      "id": "aegis_crownworks_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "aegis_crownworks_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "aegis_crownworks_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "aegis_crownworks_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "aegis_crownworks_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "dawnline_expanse": [
    {
      "id": "dawnline_expanse_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "dawnline_expanse_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "dawnline_expanse_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "dawnline_expanse_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "dawnline_expanse_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "shatterline_expanse": [
    {
      "id": "shatterline_expanse_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "shatterline_expanse_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "shatterline_expanse_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "shatterline_expanse_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "shatterline_expanse_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "rift_crownworks": [
    {
      "id": "rift_crownworks_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "rift_crownworks_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "rift_crownworks_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "rift_crownworks_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "rift_crownworks_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "rift_gate_fortress": [
    {
      "id": "rift_gate_fortress_west_objective",
      "type": "battle_objective",
      "label": "West Siege Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "rift_gate_fortress_central_objective",
      "type": "battle_objective",
      "label": "Central Siege Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "rift_gate_fortress_east_objective",
      "type": "battle_objective",
      "label": "East Siege Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "rift_gate_fortress_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "rift_gate_fortress_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "riftspire_capital": [
    {
      "id": "riftspire_capital_city_gate",
      "label": "Chainwake Bridgehead",
      "x": 0,
      "y": -105,
      "z": 12,
      "type": "city_gate",
      "captureRadius": 12,
      "defaultRealm": "riftbound"
    },
    {
      "id": "riftspire_capital_vault",
      "label": "Blackvein Vault",
      "x": 0,
      "y": -105,
      "z": -420,
      "type": "battle_objective",
      "captureRadius": 12,
      "defaultRealm": "riftbound",
      "requiresObjectiveIds": [
        "riftspire_capital_city_gate"
      ]
    },
    {
      "id": "riftspire_capital_plaza",
      "label": "Riftspire Throne",
      "x": 0,
      "y": -105,
      "z": -480,
      "type": "battle_objective",
      "captureRadius": 12,
      "defaultRealm": "riftbound",
      "requiresObjectiveIds": [
        "riftspire_capital_city_gate",
        "riftspire_capital_vault"
      ]
    }
  ],
  "sunmeadow_march": [
    {
      "id": "sunmeadow_march_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "sunmeadow_march_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "sunmeadow_march_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "sunmeadow_march_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "sunmeadow_march_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "greybrook_crossing": [
    {
      "id": "greybrook_crossing_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "greybrook_crossing_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "greybrook_crossing_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "greybrook_crossing_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "greybrook_crossing_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "ironwood_redoubt": [
    {
      "id": "ironwood_redoubt_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "ironwood_redoubt_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "ironwood_redoubt_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "ironwood_redoubt_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "ironwood_redoubt_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "brightfen_approach": [
    {
      "id": "brightfen_approach_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "brightfen_approach_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "brightfen_approach_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "brightfen_approach_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "brightfen_approach_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "glassriver_ford": [
    {
      "id": "glassriver_ford_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "glassriver_ford_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "glassriver_ford_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "glassriver_ford_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "glassriver_ford_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "highvale_rampart": [
    {
      "id": "highvale_rampart_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "highvale_rampart_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "highvale_rampart_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "highvale_rampart_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "highvale_rampart_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "cinderfen_outskirts": [
    {
      "id": "cinderfen_outskirts_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "cinderfen_outskirts_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "cinderfen_outskirts_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "cinderfen_outskirts_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "cinderfen_outskirts_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "bleakroot_causeway": [
    {
      "id": "bleakroot_causeway_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "bleakroot_causeway_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "bleakroot_causeway_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "bleakroot_causeway_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "bleakroot_causeway_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "vilemere_heights": [
    {
      "id": "vilemere_heights_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "vilemere_heights_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "vilemere_heights_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "vilemere_heights_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "vilemere_heights_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "ashen_steppe": [
    {
      "id": "ashen_steppe_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "ashen_steppe_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "ashen_steppe_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "ashen_steppe_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "ashen_steppe_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "gorepine_pass": [
    {
      "id": "gorepine_pass_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "gorepine_pass_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "gorepine_pass_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "gorepine_pass_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "gorepine_pass_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "obsidian_scar": [
    {
      "id": "obsidian_scar_west_objective",
      "type": "battle_objective",
      "label": "West Field Standard",
      "x": 0,
      "z": -260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "obsidian_scar_central_objective",
      "type": "battle_objective",
      "label": "Central Field Standard",
      "x": 0,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "obsidian_scar_east_objective",
      "type": "battle_objective",
      "label": "East Field Standard",
      "x": 0,
      "z": 260,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    },
    {
      "id": "obsidian_scar_aegis_keep",
      "type": "keep",
      "label": "Aegis War Keep",
      "x": -350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    },
    {
      "id": "obsidian_scar_riftbound_keep",
      "type": "keep",
      "label": "Riftbound War Keep",
      "x": 350,
      "z": 0,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "wardens_hollow": [
    {
      "id": "wardens_hollow_boss",
      "type": "boss",
      "label": "Warden's Hollow Overlord",
      "x": 0,
      "z": 48,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    }
  ],
  "briarwatch_den": [
    {
      "id": "briarwatch_den_boss",
      "type": "boss",
      "label": "Briarwatch Den Overlord",
      "x": 0,
      "z": 48,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    }
  ],
  "stormbarrow_lair": [
    {
      "id": "stormbarrow_lair_boss",
      "type": "boss",
      "label": "Stormbarrow Lair Overlord",
      "x": 0,
      "z": 48,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    }
  ],
  "mireglass_den": [
    {
      "id": "mireglass_den_boss",
      "type": "boss",
      "label": "Mireglass Den Overlord",
      "x": 0,
      "z": 48,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    }
  ],
  "glassriver_depths": [
    {
      "id": "glassriver_depths_boss",
      "type": "boss",
      "label": "Glassriver Depths Overlord",
      "x": 0,
      "z": 48,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    }
  ],
  "highvale_sanctum": [
    {
      "id": "highvale_sanctum_boss",
      "type": "boss",
      "label": "Highvale Sanctum Overlord",
      "x": 0,
      "z": 48,
      "captureRadius": 18,
      "defaultRealm": "aegis"
    }
  ],
  "cindermaw_pit": [
    {
      "id": "cindermaw_pit_boss",
      "type": "boss",
      "label": "Cindermaw Pit Overlord",
      "x": 0,
      "z": 48,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "rotwreath_nest": [
    {
      "id": "rotwreath_nest_boss",
      "type": "boss",
      "label": "Rotwreath Nest Overlord",
      "x": 0,
      "z": 48,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "nightglass_hollow": [
    {
      "id": "nightglass_hollow_boss",
      "type": "boss",
      "label": "Nightglass Hollow Overlord",
      "x": 0,
      "z": 48,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "ashfang_pit": [
    {
      "id": "ashfang_pit_boss",
      "type": "boss",
      "label": "Ashfang Pit Overlord",
      "x": 0,
      "z": 48,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "gorepine_warrens": [
    {
      "id": "gorepine_warrens_boss",
      "type": "boss",
      "label": "Gorepine Warrens Overlord",
      "x": 0,
      "z": 48,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ],
  "obsidian_maw": [
    {
      "id": "obsidian_maw_boss",
      "type": "boss",
      "label": "Obsidian Maw Overlord",
      "x": 0,
      "z": 48,
      "captureRadius": 18,
      "defaultRealm": "riftbound"
    }
  ]
} as const;

export const CAMPAIGN_MAP_HASHES = {
  "aegis_capital": "377d653c3b4ae130",
  "aegis_gate_fortress": "f172c92d101d3225",
  "aegis_crownworks": "b59275b498b06b0f",
  "dawnline_expanse": "216fb79fac1d3599",
  "shatterline_expanse": "676428efbba4a390",
  "rift_crownworks": "46736cea1e78fe02",
  "rift_gate_fortress": "bcb5ea1934a1fba5",
  "riftspire_capital": "7534a54b6d02d4b3",
  "sunmeadow_march": "31d3e4fff98eb6be",
  "greybrook_crossing": "3c66e8dd6ef4547d",
  "ironwood_redoubt": "9425337076c8051b",
  "brightfen_approach": "7b9908d54fe63dcc",
  "glassriver_ford": "720aa8456a275448",
  "highvale_rampart": "556a438c1bd1c30d",
  "cinderfen_outskirts": "14fb64f2045f527b",
  "bleakroot_causeway": "0af88d0094148108",
  "vilemere_heights": "d178694b45279d2b",
  "ashen_steppe": "b4eaa8053c507a02",
  "gorepine_pass": "0038e7a9378b52f5",
  "obsidian_scar": "9b4236846440d189",
  "wardens_hollow": "4585f5a6200091f4",
  "briarwatch_den": "70cba516beaffdf7",
  "stormbarrow_lair": "151cc53296644823",
  "mireglass_den": "eecba7b9165cbe77",
  "glassriver_depths": "b23a82527e4d7dbb",
  "highvale_sanctum": "5847a5296c50b785",
  "cindermaw_pit": "82a0e5b5d58647c8",
  "rotwreath_nest": "9ce17ec3615d5ff2",
  "nightglass_hollow": "b06bca1e8e6d8da8",
  "ashfang_pit": "b1f4c36b6135bb92",
  "gorepine_warrens": "debd377673540433",
  "obsidian_maw": "07c3a7f0567d9ef1"
} as const;
