// Generated by scripts/blender-character-pipeline/tools/sync-playable-assets.mjs.
// Do not edit by hand.
import type { BodyVariant, PlayableRace } from './careers';
import { normalizeClassName } from './careers';
import type { EquipmentState, EquipSlot, InventoryItem } from '../services/types';

export interface PlayableArmorProfile {
  slot: EquipSlot;
  itemKey: string;
  model: string;
  assetId: string;
  name: string;
  icon: string;
  coveredRegions: string[];
}

export interface PlayableCharacterProfile {
  race: PlayableRace;
  className: string;
  bodyVariant: BodyVariant;
  profileKey: string;
  assetId: string;
  model: string;
  bodyFamily: string;
  skeletonId: string;
  armor: Record<string, PlayableArmorProfile>;
}

const CLASS_SEEDS: Array<{ race: PlayableRace; className: string; family: string; key: string }> = [
  {
    "race": "empire",
    "className": "Ember Arcanist",
    "family": "civic",
    "key": "ember_arcanist"
  },
  {
    "race": "empire",
    "className": "Hex Inquisitor",
    "family": "civic",
    "key": "hex_inquisitor"
  },
  {
    "race": "empire",
    "className": "Sunfire Templar",
    "family": "civic",
    "key": "sunfire_templar"
  },
  {
    "race": "empire",
    "className": "Battle Prelate",
    "family": "civic",
    "key": "battle_prelate"
  },
  {
    "race": "dwarf",
    "className": "Stoneguard",
    "family": "stone",
    "key": "stoneguard"
  },
  {
    "race": "dwarf",
    "className": "Doomseeker",
    "family": "stone",
    "key": "doomseeker"
  },
  {
    "race": "dwarf",
    "className": "Glyphbinder",
    "family": "stone",
    "key": "glyphbinder"
  },
  {
    "race": "dwarf",
    "className": "Siegewright",
    "family": "stone",
    "key": "siegewright"
  },
  {
    "race": "high_elf",
    "className": "Blade Savant",
    "family": "aether",
    "key": "blade_savant"
  },
  {
    "race": "high_elf",
    "className": "Pride Warden",
    "family": "aether",
    "key": "pride_warden"
  },
  {
    "race": "high_elf",
    "className": "Aether Sage",
    "family": "aether",
    "key": "aether_sage"
  },
  {
    "race": "high_elf",
    "className": "Veil Ranger",
    "family": "aether",
    "key": "veil_ranger"
  },
  {
    "race": "chaos",
    "className": "Dreadsworn",
    "family": "riven",
    "key": "dreadsworn"
  },
  {
    "race": "chaos",
    "className": "Warped Reaver",
    "family": "riven",
    "key": "warped_reaver"
  },
  {
    "race": "chaos",
    "className": "Void Magister",
    "family": "riven",
    "key": "void_magister"
  },
  {
    "race": "chaos",
    "className": "Ruin Oracle",
    "family": "riven",
    "key": "ruin_oracle"
  },
  {
    "race": "greenskin",
    "className": "Warbrute",
    "family": "mire",
    "key": "warbrute"
  },
  {
    "race": "greenskin",
    "className": "Fang Herder",
    "family": "mire",
    "key": "fang_herder"
  },
  {
    "race": "greenskin",
    "className": "Bog Hexer",
    "family": "mire",
    "key": "bog_hexer"
  },
  {
    "race": "greenskin",
    "className": "Cleaver",
    "family": "mire",
    "key": "cleaver"
  },
  {
    "race": "dark_elf",
    "className": "Blood Dancer",
    "family": "umbra",
    "key": "blood_dancer"
  },
  {
    "race": "dark_elf",
    "className": "Dread Guard",
    "family": "umbra",
    "key": "dread_guard"
  },
  {
    "race": "dark_elf",
    "className": "Dusk Weaver",
    "family": "umbra",
    "key": "dusk_weaver"
  },
  {
    "race": "dark_elf",
    "className": "Crimson Acolyte",
    "family": "umbra",
    "key": "crimson_acolyte"
  }
];
const BODY_VARIANTS: Array<{ bodyVariant: BodyVariant; label: string }> = [
  {
    "bodyVariant": "m",
    "label": "Male"
  },
  {
    "bodyVariant": "f",
    "label": "Female"
  }
];
const ARMOR_PARTS: Array<{ slot: EquipSlot; label: string; icon: string; regions: string[] }> = [
  {
    "slot": "head",
    "label": "Headgear",
    "icon": "H",
    "regions": [
      "head"
    ]
  },
  {
    "slot": "shoulders",
    "label": "Shoulders",
    "icon": "S",
    "regions": [
      "shoulders"
    ]
  },
  {
    "slot": "chest",
    "label": "Chestguard",
    "icon": "C",
    "regions": [
      "torso"
    ]
  },
  {
    "slot": "hands",
    "label": "Handguards",
    "icon": "G",
    "regions": [
      "arms",
      "hands"
    ]
  },
  {
    "slot": "waist",
    "label": "Belt",
    "icon": "B",
    "regions": [
      "waist"
    ]
  },
  {
    "slot": "legs",
    "label": "Legguards",
    "icon": "L",
    "regions": [
      "legs"
    ]
  },
  {
    "slot": "feet",
    "label": "Boots",
    "icon": "F",
    "regions": [
      "feet"
    ]
  },
  {
    "slot": "back",
    "label": "Backpiece",
    "icon": "K",
    "regions": [
      "back"
    ]
  },
  {
    "slot": "tabard",
    "label": "Tabard",
    "icon": "T",
    "regions": [
      "tabard"
    ]
  }
];

export const PLAYABLE_ARMOR_SLOTS = ARMOR_PARTS.map(({ slot }) => slot);

export const PLAYABLE_CHARACTER_PROFILES: PlayableCharacterProfile[] = CLASS_SEEDS.flatMap(
  ({ race, className, family, key }) => BODY_VARIANTS.map(({ bodyVariant, label }) => {
    const profileKey = `${family}_${key}_${bodyVariant}`;
    return {
      race,
      className,
      bodyVariant,
      profileKey,
      assetId: `chr.${family}.${key}.t1.${bodyVariant}`,
      model: `chr_${family}_${key}_t1_${bodyVariant}.glb`,
      bodyFamily: profileKey,
      skeletonId: 'humanoid_v1',
      armor: Object.fromEntries(ARMOR_PARTS.map(({ slot, label: partLabel, icon, regions }) => [slot, {
        slot,
        itemKey: `starter_${family}_${key}_${slot}_${bodyVariant}`,
        model: `arm_${family}_${key}_${slot}_t1_${bodyVariant}.glb`,
        assetId: `arm.${family}.${key}.${slot}.t1.${bodyVariant}`,
        name: `${className} ${partLabel} (${label})`,
        icon,
        coveredRegions: [...regions],
      }])),
    };
  }),
);

export const PLAYABLE_ARMOR_ITEM_CATALOG = Object.fromEntries(
  PLAYABLE_CHARACTER_PROFILES.flatMap((profile) => Object.values(profile.armor).map((armor) => [
    armor.itemKey,
    {
      key: armor.itemKey,
      name: armor.name,
      icon: armor.icon,
      kind: 'armor',
      equipSlot: armor.slot,
      visual: { model: armor.model, fallback: 'overlay' },
    },
  ] as const)),
);

export function normalizeBodyVariant(value: string | null | undefined): BodyVariant {
  return value === 'f' ? 'f' : 'm';
}

export function findPlayableCharacterProfile(
  race: PlayableRace | string,
  className: string | null | undefined,
  bodyVariant: BodyVariant | string | null | undefined = 'm',
): PlayableCharacterProfile | null {
  const normalizedClassName = normalizeClassName(className);
  const normalizedVariant = normalizeBodyVariant(bodyVariant);
  return PLAYABLE_CHARACTER_PROFILES.find((profile) =>
    profile.race === race &&
    profile.className === normalizedClassName &&
    profile.bodyVariant === normalizedVariant
  ) ?? null;
}

export function playableCharacterProfileKeyFor(
  race: PlayableRace | string,
  className: string | null | undefined,
  bodyVariant: BodyVariant | string | null | undefined = 'm',
): string {
  return findPlayableCharacterProfile(race, className, bodyVariant)?.profileKey ?? `${race}_default`;
}

export function starterArmorEquipmentFor(
  race: PlayableRace | string,
  className: string | null | undefined,
  bodyVariant: BodyVariant | string | null | undefined = 'm',
): EquipmentState {
  const profile = findPlayableCharacterProfile(race, className, bodyVariant);
  if (!profile) return {};
  const equipment: EquipmentState = {};
  for (const slot of PLAYABLE_ARMOR_SLOTS) {
    const armor = profile.armor[slot];
    if (!armor) continue;
    equipment[slot] = {
      key: armor.itemKey,
      name: armor.name,
      icon: armor.icon,
      kind: 'armor',
      equipSlot: slot,
    };
  }
  return equipment;
}

export function starterArmorInventoryFor(
  race: PlayableRace | string,
  className: string | null | undefined,
  bodyVariant: BodyVariant | string | null | undefined = 'm',
  startSlot = 5,
): InventoryItem[] {
  const profile = findPlayableCharacterProfile(race, className, bodyVariant);
  if (!profile) return [];
  const items: InventoryItem[] = [];
  PLAYABLE_ARMOR_SLOTS.forEach((slot, index) => {
    const armor = profile.armor[slot];
    if (!armor) return;
    items.push({
      slot: startSlot + index,
      key: armor.itemKey,
      name: armor.name,
      qty: 1,
      icon: armor.icon,
      kind: 'armor',
      equipSlot: slot,
    });
  });
  return items;
}
